// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package http

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UpdateRoleRequestRole.
const (
	Admin      UpdateRoleRequestRole = "admin"
	Superadmin UpdateRoleRequestRole = "superadmin"
	User       UpdateRoleRequestRole = "user"
)

// Valid indicates whether the value is a known member of the UpdateRoleRequestRole enum.
func (e UpdateRoleRequestRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Superadmin:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for UpdateStatusRequestStatus.
const (
	Active   UpdateStatusRequestStatus = "active"
	Deleted  UpdateStatusRequestStatus = "deleted"
	Disabled UpdateStatusRequestStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UpdateStatusRequestStatus enum.
func (e UpdateStatusRequestStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Deleted:
		return true
	case Disabled:
		return true
	default:
		return false
	}
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	NewPassword string `json:"new_password"`
	Password    string `json:"password"`
	SignOutAll  *bool  `json:"sign_out_all,omitempty"`
}

// CreateSuperadminRequest Credentials and optional display name for the initial system owner.
type CreateSuperadminRequest struct {
	Email    openapi_types.Email `json:"email"`
	FullName *string             `json:"full_name,omitempty"`
	Password string              `json:"password"`
}

// CredentialsRequest defines model for CredentialsRequest.
type CredentialsRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	EntityId   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	ErrorSlug  string `json:"error_slug"`
	Message    string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details []ErrorDetail `json:"details"`
	Message string        `json:"message"`
	Slug    string        `json:"slug"`
}

// SignUpRequest defines model for SignUpRequest.
type SignUpRequest struct {
	Email    openapi_types.Email `json:"email"`
	FullName *string             `json:"full_name,omitempty"`
	Password string              `json:"password"`
}

// Tokens defines model for Tokens.
type Tokens struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
	TokenType   string `json:"token_type"`
}

// UpdateFullNameRequest defines model for UpdateFullNameRequest.
type UpdateFullNameRequest struct {
	FullName string `json:"full_name"`
}

// UpdateRoleRequest defines model for UpdateRoleRequest.
type UpdateRoleRequest struct {
	Role UpdateRoleRequestRole `json:"role"`
}

// UpdateRoleRequestRole defines model for UpdateRoleRequest.Role.
type UpdateRoleRequestRole string

// UpdateStatusRequest defines model for UpdateStatusRequest.
type UpdateStatusRequest struct {
	Status UpdateStatusRequestStatus `json:"status"`
}

// UpdateStatusRequestStatus defines model for UpdateStatusRequest.Status.
type UpdateStatusRequestStatus string

// UserCreated defines model for UserCreated.
type UserCreated struct {
	Id openapi_types.UUID `json:"id"`
}

// UserID defines model for UserID.
type UserID = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// CreateSuperadminJSONRequestBody defines body for CreateSuperadmin for application/json ContentType.
type CreateSuperadminJSONRequestBody = CreateSuperadminRequest

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody = CredentialsRequest

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody = SignUpRequest

// UpdateFullNameJSONRequestBody defines body for UpdateFullName for application/json ContentType.
type UpdateFullNameJSONRequestBody = UpdateFullNameRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// UpdateUserRoleJSONRequestBody defines body for UpdateUserRole for application/json ContentType.
type UpdateUserRoleJSONRequestBody = UpdateRoleRequest

// UpdateUserStatusJSONRequestBody defines body for UpdateUserStatus for application/json ContentType.
type UpdateUserStatusJSONRequestBody = UpdateStatusRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateSuperadmin Create the initial superadmin account
	// (POST /internal/superadmin)
	CreateSuperadmin(ctx *echo.Context) error
	// RefreshToken Refresh an authenticated session
	// (POST /refresh-token)
	RefreshToken(ctx *echo.Context) error
	// SignIn Sign in
	// (POST /sign-in)
	SignIn(ctx *echo.Context) error
	// SignOutAllDevices Sign out all devices
	// (POST /sign-out-all-devices)
	SignOutAllDevices(ctx *echo.Context) error
	// SignUp Register a user account
	// (POST /sign-up)
	SignUp(ctx *echo.Context) error
	// UpdateFullName Change the current user's full name
	// (PATCH /users/{id}/full-name)
	UpdateFullName(ctx *echo.Context, id UserID) error
	// ChangePassword Change the current user's password
	// (PUT /users/{id}/password)
	ChangePassword(ctx *echo.Context, id UserID) error
	// UpdateUserRole Change another account's role
	// (PATCH /users/{id}/role)
	UpdateUserRole(ctx *echo.Context, id UserID) error
	// UpdateUserStatus Change the current user's status
	// (PATCH /users/{id}/status)
	UpdateUserStatus(ctx *echo.Context, id UserID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateSuperadmin converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSuperadmin(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSuperadmin(ctx)
	return err
}

// RefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshToken(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshToken(ctx)
	return err
}

// SignIn converts echo context to params.
func (w *ServerInterfaceWrapper) SignIn(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignIn(ctx)
	return err
}

// SignOutAllDevices converts echo context to params.
func (w *ServerInterfaceWrapper) SignOutAllDevices(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignOutAllDevices(ctx)
	return err
}

// SignUp converts echo context to params.
func (w *ServerInterfaceWrapper) SignUp(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignUp(ctx)
	return err
}

// UpdateFullName converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateFullName(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id UserID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateFullName(ctx, id)
	return err
}

// ChangePassword converts echo context to params.
func (w *ServerInterfaceWrapper) ChangePassword(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id UserID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ChangePassword(ctx, id)
	return err
}

// UpdateUserRole converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserRole(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id UserID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserRole(ctx, id)
	return err
}

// UpdateUserStatus converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserStatus(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id UserID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserStatus(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/internal/superadmin", wrapper.CreateSuperadmin, options.OperationMiddlewares["createSuperadmin"]...)
	router.POST(options.BaseURL+"/sign-up", wrapper.SignUp, options.OperationMiddlewares["signUp"]...)
	router.POST(options.BaseURL+"/sign-in", wrapper.SignIn, options.OperationMiddlewares["signIn"]...)
	router.POST(options.BaseURL+"/refresh-token", wrapper.RefreshToken, options.OperationMiddlewares["refreshToken"]...)
	router.POST(options.BaseURL+"/sign-out-all-devices", wrapper.SignOutAllDevices, options.OperationMiddlewares["signOutAllDevices"]...)
	router.PUT(options.BaseURL+"/users/:id/password", wrapper.ChangePassword, options.OperationMiddlewares["changePassword"]...)
	router.PATCH(options.BaseURL+"/users/:id/full-name", wrapper.UpdateFullName, options.OperationMiddlewares["updateFullName"]...)
	router.PATCH(options.BaseURL+"/users/:id/status", wrapper.UpdateUserStatus, options.OperationMiddlewares["updateUserStatus"]...)
	router.PATCH(options.BaseURL+"/users/:id/role", wrapper.UpdateUserRole, options.OperationMiddlewares["updateUserRole"]...)

}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type TokensJSONResponse Tokens

type UnauthorizedJSONResponse ErrorResponse

type UserCreatedJSONResponse UserCreated

type CreateSuperadminRequestObject struct {
	Body *CreateSuperadminJSONRequestBody
}

type CreateSuperadminResponseObject interface {
	VisitCreateSuperadminResponse(w http.ResponseWriter) error
}

type CreateSuperadmin201JSONResponse struct{ UserCreatedJSONResponse }

func (response CreateSuperadmin201JSONResponse) VisitCreateSuperadminResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSuperadmin400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSuperadmin400JSONResponse) VisitCreateSuperadminResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSuperadmin409JSONResponse struct{ ConflictJSONResponse }

func (response CreateSuperadmin409JSONResponse) VisitCreateSuperadminResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSuperadmin500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateSuperadmin500JSONResponse) VisitCreateSuperadminResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse struct{ TokensJSONResponse }

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SignInRequestObject struct {
	Body *SignInJSONRequestBody
}

type SignInResponseObject interface {
	VisitSignInResponse(w http.ResponseWriter) error
}

type SignIn200JSONResponse struct{ TokensJSONResponse }

func (response SignIn200JSONResponse) VisitSignInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SignIn400JSONResponse struct{ BadRequestJSONResponse }

func (response SignIn400JSONResponse) VisitSignInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SignIn401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SignIn401JSONResponse) VisitSignInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SignOutAllDevicesRequestObject struct {
}

type SignOutAllDevicesResponseObject interface {
	VisitSignOutAllDevicesResponse(w http.ResponseWriter) error
}

type SignOutAllDevices204Response struct {
}

func (response SignOutAllDevices204Response) VisitSignOutAllDevicesResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SignOutAllDevices401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SignOutAllDevices401JSONResponse) VisitSignOutAllDevicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SignUpRequestObject struct {
	Body *SignUpJSONRequestBody
}

type SignUpResponseObject interface {
	VisitSignUpResponse(w http.ResponseWriter) error
}

type SignUp201JSONResponse struct{ UserCreatedJSONResponse }

func (response SignUp201JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type SignUp400JSONResponse struct{ BadRequestJSONResponse }

func (response SignUp400JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SignUp409JSONResponse struct{ ConflictJSONResponse }

func (response SignUp409JSONResponse) VisitSignUpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateFullNameRequestObject struct {
	Id   UserID `json:"id"`
	Body *UpdateFullNameJSONRequestBody
}

type UpdateFullNameResponseObject interface {
	VisitUpdateFullNameResponse(w http.ResponseWriter) error
}

type UpdateFullName204Response struct {
}

func (response UpdateFullName204Response) VisitUpdateFullNameResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateFullName400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateFullName400JSONResponse) VisitUpdateFullNameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateFullName401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateFullName401JSONResponse) VisitUpdateFullNameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateFullName403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateFullName403JSONResponse) VisitUpdateFullNameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateFullName404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateFullName404JSONResponse) VisitUpdateFullNameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePasswordRequestObject struct {
	Id   UserID `json:"id"`
	Body *ChangePasswordJSONRequestBody
}

type ChangePasswordResponseObject interface {
	VisitChangePasswordResponse(w http.ResponseWriter) error
}

type ChangePassword204Response struct {
}

func (response ChangePassword204Response) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ChangePassword400JSONResponse struct{ BadRequestJSONResponse }

func (response ChangePassword400JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePassword401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ChangePassword401JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePassword403JSONResponse struct{ ForbiddenJSONResponse }

func (response ChangePassword403JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePassword404JSONResponse struct{ NotFoundJSONResponse }

func (response ChangePassword404JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserRoleRequestObject struct {
	Id   UserID `json:"id"`
	Body *UpdateUserRoleJSONRequestBody
}

type UpdateUserRoleResponseObject interface {
	VisitUpdateUserRoleResponse(w http.ResponseWriter) error
}

type UpdateUserRole204Response struct {
}

func (response UpdateUserRole204Response) VisitUpdateUserRoleResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateUserRole400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateUserRole400JSONResponse) VisitUpdateUserRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserRole401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateUserRole401JSONResponse) VisitUpdateUserRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserRole403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateUserRole403JSONResponse) VisitUpdateUserRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserRole404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateUserRole404JSONResponse) VisitUpdateUserRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserStatusRequestObject struct {
	Id   UserID `json:"id"`
	Body *UpdateUserStatusJSONRequestBody
}

type UpdateUserStatusResponseObject interface {
	VisitUpdateUserStatusResponse(w http.ResponseWriter) error
}

type UpdateUserStatus204Response struct {
}

func (response UpdateUserStatus204Response) VisitUpdateUserStatusResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateUserStatus400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateUserStatus400JSONResponse) VisitUpdateUserStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserStatus401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateUserStatus401JSONResponse) VisitUpdateUserStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserStatus403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateUserStatus403JSONResponse) VisitUpdateUserStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserStatus404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateUserStatus404JSONResponse) VisitUpdateUserStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateSuperadmin Create the initial superadmin account
	// (POST /internal/superadmin)
	CreateSuperadmin(ctx context.Context, request CreateSuperadminRequestObject) (CreateSuperadminResponseObject, error)
	// RefreshToken Refresh an authenticated session
	// (POST /refresh-token)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// SignIn Sign in
	// (POST /sign-in)
	SignIn(ctx context.Context, request SignInRequestObject) (SignInResponseObject, error)
	// SignOutAllDevices Sign out all devices
	// (POST /sign-out-all-devices)
	SignOutAllDevices(ctx context.Context, request SignOutAllDevicesRequestObject) (SignOutAllDevicesResponseObject, error)
	// SignUp Register a user account
	// (POST /sign-up)
	SignUp(ctx context.Context, request SignUpRequestObject) (SignUpResponseObject, error)
	// UpdateFullName Change the current user's full name
	// (PATCH /users/{id}/full-name)
	UpdateFullName(ctx context.Context, request UpdateFullNameRequestObject) (UpdateFullNameResponseObject, error)
	// ChangePassword Change the current user's password
	// (PUT /users/{id}/password)
	ChangePassword(ctx context.Context, request ChangePasswordRequestObject) (ChangePasswordResponseObject, error)
	// UpdateUserRole Change another account's role
	// (PATCH /users/{id}/role)
	UpdateUserRole(ctx context.Context, request UpdateUserRoleRequestObject) (UpdateUserRoleResponseObject, error)
	// UpdateUserStatus Change the current user's status
	// (PATCH /users/{id}/status)
	UpdateUserStatus(ctx context.Context, request UpdateUserStatusRequestObject) (UpdateUserStatusResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateSuperadmin operation middleware
func (sh *strictHandler) CreateSuperadmin(ctx *echo.Context) error {
	var request CreateSuperadminRequestObject

	var body CreateSuperadminJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSuperadmin(ctx.Request().Context(), request.(CreateSuperadminRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSuperadmin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateSuperadminResponseObject); ok {
		return validResponse.VisitCreateSuperadminResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx *echo.Context) error {
	var request RefreshTokenRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx.Request().Context(), request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		return validResponse.VisitRefreshTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SignIn operation middleware
func (sh *strictHandler) SignIn(ctx *echo.Context) error {
	var request SignInRequestObject

	var body SignInJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SignIn(ctx.Request().Context(), request.(SignInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SignIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SignInResponseObject); ok {
		return validResponse.VisitSignInResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SignOutAllDevices operation middleware
func (sh *strictHandler) SignOutAllDevices(ctx *echo.Context) error {
	var request SignOutAllDevicesRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SignOutAllDevices(ctx.Request().Context(), request.(SignOutAllDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SignOutAllDevices")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SignOutAllDevicesResponseObject); ok {
		return validResponse.VisitSignOutAllDevicesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SignUp operation middleware
func (sh *strictHandler) SignUp(ctx *echo.Context) error {
	var request SignUpRequestObject

	var body SignUpJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SignUp(ctx.Request().Context(), request.(SignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SignUpResponseObject); ok {
		return validResponse.VisitSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateFullName operation middleware
func (sh *strictHandler) UpdateFullName(ctx *echo.Context, id UserID) error {
	var request UpdateFullNameRequestObject

	request.Id = id

	var body UpdateFullNameJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateFullName(ctx.Request().Context(), request.(UpdateFullNameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateFullName")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateFullNameResponseObject); ok {
		return validResponse.VisitUpdateFullNameResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ChangePassword operation middleware
func (sh *strictHandler) ChangePassword(ctx *echo.Context, id UserID) error {
	var request ChangePasswordRequestObject

	request.Id = id

	var body ChangePasswordJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePassword(ctx.Request().Context(), request.(ChangePasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ChangePasswordResponseObject); ok {
		return validResponse.VisitChangePasswordResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateUserRole operation middleware
func (sh *strictHandler) UpdateUserRole(ctx *echo.Context, id UserID) error {
	var request UpdateUserRoleRequestObject

	request.Id = id

	var body UpdateUserRoleJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserRole(ctx.Request().Context(), request.(UpdateUserRoleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserRole")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateUserRoleResponseObject); ok {
		return validResponse.VisitUpdateUserRoleResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateUserStatus operation middleware
func (sh *strictHandler) UpdateUserStatus(ctx *echo.Context, id UserID) error {
	var request UpdateUserStatusRequestObject

	request.Id = id

	var body UpdateUserStatusJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserStatus(ctx.Request().Context(), request.(UpdateUserStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateUserStatusResponseObject); ok {
		return validResponse.VisitUpdateUserStatusResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
