// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointment_idempotency.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointmentIdempotency = `-- name: CreateAppointmentIdempotency :exec
INSERT INTO appointment_scheduler.appointment_idempotency (idempotency_key, appointment_id, created_at)
VALUES ($1, $2, $3)
`

type CreateAppointmentIdempotencyParams struct {
	IdempotencyKey string
	AppointmentID  pgtype.UUID
	CreatedAt      time.Time
}

func (q *Queries) CreateAppointmentIdempotency(ctx context.Context, arg CreateAppointmentIdempotencyParams) error {
	_, err := q.db.Exec(ctx, createAppointmentIdempotency, arg.IdempotencyKey, arg.AppointmentID, arg.CreatedAt)
	return err
}

const deleteAppointmentIdempotency = `-- name: DeleteAppointmentIdempotency :execrows
UPDATE appointment_scheduler.appointment_idempotency
SET deleted_at = $1::timestamptz
WHERE idempotency_key = $2 AND deleted_at IS NULL
`

type DeleteAppointmentIdempotencyParams struct {
	DeletedAt      time.Time
	IdempotencyKey string
}

func (q *Queries) DeleteAppointmentIdempotency(ctx context.Context, arg DeleteAppointmentIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAppointmentIdempotency, arg.DeletedAt, arg.IdempotencyKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppointmentIdempotency = `-- name: GetAppointmentIdempotency :one

SELECT idempotency_key, appointment_id, created_at, deleted_at
FROM appointment_scheduler.appointment_idempotency
WHERE idempotency_key = $1 AND deleted_at IS NULL
`

// appointment idempotency CRUD queries.
func (q *Queries) GetAppointmentIdempotency(ctx context.Context, idempotencyKey string) (AppointmentSchedulerAppointmentIdempotency, error) {
	row := q.db.QueryRow(ctx, getAppointmentIdempotency, idempotencyKey)
	var i AppointmentSchedulerAppointmentIdempotency
	err := row.Scan(
		&i.IdempotencyKey,
		&i.AppointmentID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAppointmentIdempotency = `-- name: UpdateAppointmentIdempotency :execrows
UPDATE appointment_scheduler.appointment_idempotency
SET appointment_id = $1
WHERE idempotency_key = $2 AND deleted_at IS NULL
`

type UpdateAppointmentIdempotencyParams struct {
	AppointmentID  pgtype.UUID
	IdempotencyKey string
}

func (q *Queries) UpdateAppointmentIdempotency(ctx context.Context, arg UpdateAppointmentIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAppointmentIdempotency, arg.AppointmentID, arg.IdempotencyKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
