// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointment_resource_reservations.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointmentResourceReservation = `-- name: CreateAppointmentResourceReservation :exec
INSERT INTO appointment_scheduler.appointment_resource_reservations (
  appointment_resource_reservation_id, appointment_id, resource_type, resource_id,
  reserved_starts_at, reserved_ends_at, status, assigned_at, assigned_by_user_id, reason
) VALUES (
  $1, $2,
  $3, $4, $5,
  $6, $7, $8,
  $9, $10
)
`

type CreateAppointmentResourceReservationParams struct {
	AppointmentResourceReservationID pgtype.UUID
	AppointmentID                    pgtype.UUID
	ResourceType                     string
	ResourceID                       pgtype.UUID
	ReservedStartsAt                 time.Time
	ReservedEndsAt                   time.Time
	Status                           string
	AssignedAt                       time.Time
	AssignedByUserID                 pgtype.UUID
	Reason                           *string
}

func (q *Queries) CreateAppointmentResourceReservation(ctx context.Context, arg CreateAppointmentResourceReservationParams) error {
	_, err := q.db.Exec(ctx, createAppointmentResourceReservation,
		arg.AppointmentResourceReservationID,
		arg.AppointmentID,
		arg.ResourceType,
		arg.ResourceID,
		arg.ReservedStartsAt,
		arg.ReservedEndsAt,
		arg.Status,
		arg.AssignedAt,
		arg.AssignedByUserID,
		arg.Reason,
	)
	return err
}

const listAppointmentResourceReservations = `-- name: ListAppointmentResourceReservations :many
SELECT appointment_resource_reservation_id, appointment_id, resource_type, resource_id,
  reserved_starts_at, reserved_ends_at, status, assigned_at, released_at,
  assigned_by_user_id, reason
FROM appointment_scheduler.appointment_resource_reservations
WHERE appointment_id = $1
ORDER BY assigned_at, appointment_resource_reservation_id
`

func (q *Queries) ListAppointmentResourceReservations(ctx context.Context, appointmentID pgtype.UUID) ([]AppointmentSchedulerAppointmentResourceReservation, error) {
	rows, err := q.db.Query(ctx, listAppointmentResourceReservations, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppointmentSchedulerAppointmentResourceReservation{}
	for rows.Next() {
		var i AppointmentSchedulerAppointmentResourceReservation
		if err := rows.Scan(
			&i.AppointmentResourceReservationID,
			&i.AppointmentID,
			&i.ResourceType,
			&i.ResourceID,
			&i.ReservedStartsAt,
			&i.ReservedEndsAt,
			&i.Status,
			&i.AssignedAt,
			&i.ReleasedAt,
			&i.AssignedByUserID,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAppointmentResourceReservations = `-- name: ReleaseAppointmentResourceReservations :execrows
UPDATE appointment_scheduler.appointment_resource_reservations
SET released_at = $1, status = $2
WHERE appointment_id = $3
  AND released_at IS NULL
`

type ReleaseAppointmentResourceReservationsParams struct {
	ReleasedAt    pgtype.Timestamptz
	Status        string
	AppointmentID pgtype.UUID
}

func (q *Queries) ReleaseAppointmentResourceReservations(ctx context.Context, arg ReleaseAppointmentResourceReservationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseAppointmentResourceReservations, arg.ReleasedAt, arg.Status, arg.AppointmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
