// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointments = `-- name: CreateAppointments :exec
INSERT INTO appointment_scheduler.appointments (appointment_id, reference_code, customer_id, vehicle_id, dealership_id, service_type_id, technician_id, service_bay_id, starts_at, ends_at, status, notes, created_by_user_id, cancelled_by_user_id, cancellation_reason, created_at, updated_at, cancelled_at, checked_in_at, started_at, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
`

type CreateAppointmentsParams struct {
	AppointmentID      pgtype.UUID
	ReferenceCode      string
	CustomerID         pgtype.UUID
	VehicleID          pgtype.UUID
	DealershipID       pgtype.UUID
	ServiceTypeID      pgtype.UUID
	TechnicianID       pgtype.UUID
	ServiceBayID       pgtype.UUID
	StartsAt           time.Time
	EndsAt             time.Time
	Status             string
	Notes              *string
	CreatedByUserID    pgtype.UUID
	CancelledByUserID  pgtype.UUID
	CancellationReason *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	CancelledAt        pgtype.Timestamptz
	CheckedInAt        pgtype.Timestamptz
	StartedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
}

func (q *Queries) CreateAppointments(ctx context.Context, arg CreateAppointmentsParams) error {
	_, err := q.db.Exec(ctx, createAppointments,
		arg.AppointmentID,
		arg.ReferenceCode,
		arg.CustomerID,
		arg.VehicleID,
		arg.DealershipID,
		arg.ServiceTypeID,
		arg.TechnicianID,
		arg.ServiceBayID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.Notes,
		arg.CreatedByUserID,
		arg.CancelledByUserID,
		arg.CancellationReason,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CancelledAt,
		arg.CheckedInAt,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const deleteAppointments = `-- name: DeleteAppointments :execrows
UPDATE appointment_scheduler.appointments
SET deleted_at = $1::timestamptz
WHERE appointment_id = $2 AND deleted_at IS NULL
`

type DeleteAppointmentsParams struct {
	DeletedAt     time.Time
	AppointmentID pgtype.UUID
}

func (q *Queries) DeleteAppointments(ctx context.Context, arg DeleteAppointmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAppointments, arg.DeletedAt, arg.AppointmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppointments = `-- name: GetAppointments :one

SELECT appointment_id, reference_code, customer_id, vehicle_id, dealership_id, service_type_id, technician_id, service_bay_id, starts_at, ends_at, status, notes, created_by_user_id, cancelled_by_user_id, cancellation_reason, created_at, updated_at, cancelled_at, checked_in_at, started_at, completed_at, deleted_at
FROM appointment_scheduler.appointments
WHERE appointment_id = $1 AND deleted_at IS NULL
`

type GetAppointmentsRow struct {
	AppointmentID      pgtype.UUID
	ReferenceCode      string
	CustomerID         pgtype.UUID
	VehicleID          pgtype.UUID
	DealershipID       pgtype.UUID
	ServiceTypeID      pgtype.UUID
	TechnicianID       pgtype.UUID
	ServiceBayID       pgtype.UUID
	StartsAt           time.Time
	EndsAt             time.Time
	Status             string
	Notes              *string
	CreatedByUserID    pgtype.UUID
	CancelledByUserID  pgtype.UUID
	CancellationReason *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	CancelledAt        pgtype.Timestamptz
	CheckedInAt        pgtype.Timestamptz
	StartedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

// appointments CRUD queries.
func (q *Queries) GetAppointments(ctx context.Context, appointmentID pgtype.UUID) (GetAppointmentsRow, error) {
	row := q.db.QueryRow(ctx, getAppointments, appointmentID)
	var i GetAppointmentsRow
	err := row.Scan(
		&i.AppointmentID,
		&i.ReferenceCode,
		&i.CustomerID,
		&i.VehicleID,
		&i.DealershipID,
		&i.ServiceTypeID,
		&i.TechnicianID,
		&i.ServiceBayID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.Notes,
		&i.CreatedByUserID,
		&i.CancelledByUserID,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
		&i.CheckedInAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAppointments = `-- name: UpdateAppointments :execrows
UPDATE appointment_scheduler.appointments
SET reference_code = $1, customer_id = $2, vehicle_id = $3, dealership_id = $4, service_type_id = $5, technician_id = $6, service_bay_id = $7, starts_at = $8, ends_at = $9, status = $10, notes = $11, created_by_user_id = $12, cancelled_by_user_id = $13, cancellation_reason = $14, updated_at = $15, cancelled_at = $16, checked_in_at = $17, started_at = $18, completed_at = $19
WHERE appointment_id = $20 AND deleted_at IS NULL
`

type UpdateAppointmentsParams struct {
	ReferenceCode      string
	CustomerID         pgtype.UUID
	VehicleID          pgtype.UUID
	DealershipID       pgtype.UUID
	ServiceTypeID      pgtype.UUID
	TechnicianID       pgtype.UUID
	ServiceBayID       pgtype.UUID
	StartsAt           time.Time
	EndsAt             time.Time
	Status             string
	Notes              *string
	CreatedByUserID    pgtype.UUID
	CancelledByUserID  pgtype.UUID
	CancellationReason *string
	UpdatedAt          time.Time
	CancelledAt        pgtype.Timestamptz
	CheckedInAt        pgtype.Timestamptz
	StartedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	AppointmentID      pgtype.UUID
}

func (q *Queries) UpdateAppointments(ctx context.Context, arg UpdateAppointmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAppointments,
		arg.ReferenceCode,
		arg.CustomerID,
		arg.VehicleID,
		arg.DealershipID,
		arg.ServiceTypeID,
		arg.TechnicianID,
		arg.ServiceBayID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.Notes,
		arg.CreatedByUserID,
		arg.CancelledByUserID,
		arg.CancellationReason,
		arg.UpdatedAt,
		arg.CancelledAt,
		arg.CheckedInAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.AppointmentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
