// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointment_audit_events.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointmentAuditEvents = `-- name: CreateAppointmentAuditEvents :exec

INSERT INTO appointment_scheduler.appointment_audit_events (appointment_audit_event_id, appointment_id, actor_user_id, event_type, before_data, after_data, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAppointmentAuditEventsParams struct {
	AppointmentAuditEventID pgtype.UUID
	AppointmentID           pgtype.UUID
	ActorUserID             pgtype.UUID
	EventType               string
	BeforeData              []byte
	AfterData               []byte
	OccurredAt              time.Time
}

// Appointment audit events are append-only. Only creation and read projection
// queries belong here; updates and deletes are intentionally not generated.
func (q *Queries) CreateAppointmentAuditEvents(ctx context.Context, arg CreateAppointmentAuditEventsParams) error {
	_, err := q.db.Exec(ctx, createAppointmentAuditEvents,
		arg.AppointmentAuditEventID,
		arg.AppointmentID,
		arg.ActorUserID,
		arg.EventType,
		arg.BeforeData,
		arg.AfterData,
		arg.OccurredAt,
	)
	return err
}
