// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO appointment_scheduler.customers (customer_id, name, phone, email, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING customer_id, name, phone, email, created_at, updated_at
`

type CreateCustomerParams struct {
	CustomerID pgtype.UUID
	Name       string
	Phone      string
	Email      *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (AppointmentSchedulerCustomer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.CustomerID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AppointmentSchedulerCustomer
	err := row.Scan(
		&i.CustomerID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT customer_id, name, phone, email, created_at, updated_at
FROM appointment_scheduler.customers
WHERE lower(email) = $1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email *string) (AppointmentSchedulerCustomer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, email)
	var i AppointmentSchedulerCustomer
	err := row.Scan(
		&i.CustomerID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT customer_id, name, phone, email, created_at, updated_at
FROM appointment_scheduler.customers
WHERE customer_id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, customerID pgtype.UUID) (AppointmentSchedulerCustomer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, customerID)
	var i AppointmentSchedulerCustomer
	err := row.Scan(
		&i.CustomerID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT customer_id, name, phone, email, created_at, updated_at
FROM appointment_scheduler.customers
WHERE phone = $1
`

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone string) (AppointmentSchedulerCustomer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, phone)
	var i AppointmentSchedulerCustomer
	err := row.Scan(
		&i.CustomerID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE appointment_scheduler.customers
SET name = $1, phone = $2, email = $3, updated_at = $4
WHERE customer_id = $5
RETURNING customer_id, name, phone, email, created_at, updated_at
`

type UpdateCustomerParams struct {
	Name       string
	Phone      string
	Email      *string
	UpdatedAt  time.Time
	CustomerID pgtype.UUID
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (AppointmentSchedulerCustomer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.UpdatedAt,
		arg.CustomerID,
	)
	var i AppointmentSchedulerCustomer
	err := row.Scan(
		&i.CustomerID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
