// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomers = `-- name: CreateCustomers :exec
INSERT INTO appointment_scheduler.customers (customer_id, name, phone, email, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateCustomersParams struct {
	CustomerID pgtype.UUID
	Name       string
	Phone      *string
	Email      *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateCustomers(ctx context.Context, arg CreateCustomersParams) error {
	_, err := q.db.Exec(ctx, createCustomers,
		arg.CustomerID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCustomers = `-- name: DeleteCustomers :execrows
UPDATE appointment_scheduler.customers
SET deleted_at = $1::timestamptz
WHERE customer_id = $2 AND deleted_at IS NULL
`

type DeleteCustomersParams struct {
	DeletedAt  time.Time
	CustomerID pgtype.UUID
}

func (q *Queries) DeleteCustomers(ctx context.Context, arg DeleteCustomersParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomers, arg.DeletedAt, arg.CustomerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomers = `-- name: GetCustomers :one

SELECT customer_id, name, phone, email, created_at, updated_at, deleted_at
FROM appointment_scheduler.customers
WHERE customer_id = $1 AND deleted_at IS NULL
`

type GetCustomersRow struct {
	CustomerID pgtype.UUID
	Name       string
	Phone      string
	Email      *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  pgtype.Timestamptz
}

// customers CRUD queries.
func (q *Queries) GetCustomers(ctx context.Context, customerID pgtype.UUID) (GetCustomersRow, error) {
	row := q.db.QueryRow(ctx, getCustomers, customerID)
	var i GetCustomersRow
	err := row.Scan(
		&i.CustomerID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCustomers = `-- name: UpdateCustomers :execrows
UPDATE appointment_scheduler.customers
SET name = $1, phone = $2, email = $3, updated_at = $4
WHERE customer_id = $5 AND deleted_at IS NULL
`

type UpdateCustomersParams struct {
	Name       string
	Phone      *string
	Email      *string
	UpdatedAt  time.Time
	CustomerID pgtype.UUID
}

func (q *Queries) UpdateCustomers(ctx context.Context, arg UpdateCustomersParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCustomers,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.UpdatedAt,
		arg.CustomerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
