// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dealerships.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDealerships = `-- name: CreateDealerships :exec
INSERT INTO appointment_scheduler.dealerships (dealership_id, name, code, address, timezone, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateDealershipsParams struct {
	DealershipID pgtype.UUID
	Name         string
	Code         string
	Address      string
	Timezone     string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateDealerships(ctx context.Context, arg CreateDealershipsParams) error {
	_, err := q.db.Exec(ctx, createDealerships,
		arg.DealershipID,
		arg.Name,
		arg.Code,
		arg.Address,
		arg.Timezone,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDealerships = `-- name: DeleteDealerships :execrows
UPDATE appointment_scheduler.dealerships
SET deleted_at = $1::timestamptz
WHERE dealership_id = $2 AND deleted_at IS NULL
`

type DeleteDealershipsParams struct {
	DeletedAt    time.Time
	DealershipID pgtype.UUID
}

func (q *Queries) DeleteDealerships(ctx context.Context, arg DeleteDealershipsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDealerships, arg.DeletedAt, arg.DealershipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveDealership = `-- name: GetActiveDealership :one
SELECT dealership_id
FROM appointment_scheduler.dealerships
WHERE dealership_id = $1
  AND is_active = TRUE
  AND deleted_at IS NULL
`

func (q *Queries) GetActiveDealership(ctx context.Context, dealershipID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveDealership, dealershipID)
	var dealership_id pgtype.UUID
	err := row.Scan(&dealership_id)
	return dealership_id, err
}

const getDealerships = `-- name: GetDealerships :one
SELECT dealership_id, name, code, address, timezone, is_active, created_at, updated_at, deleted_at
FROM appointment_scheduler.dealerships
WHERE dealership_id = $1 AND deleted_at IS NULL
`

type GetDealershipsRow struct {
	DealershipID pgtype.UUID
	Name         string
	Code         string
	Address      string
	Timezone     string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetDealerships(ctx context.Context, dealershipID pgtype.UUID) (GetDealershipsRow, error) {
	row := q.db.QueryRow(ctx, getDealerships, dealershipID)
	var i GetDealershipsRow
	err := row.Scan(
		&i.DealershipID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDealerships = `-- name: ListDealerships :many

SELECT dealership_id, name, code, address, timezone, is_active, created_at, updated_at
FROM appointment_scheduler.dealerships
WHERE deleted_at IS NULL
ORDER BY name, dealership_id
`

type ListDealershipsRow struct {
	DealershipID pgtype.UUID
	Name         string
	Code         string
	Address      string
	Timezone     string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// dealerships CRUD queries.
func (q *Queries) ListDealerships(ctx context.Context) ([]ListDealershipsRow, error) {
	rows, err := q.db.Query(ctx, listDealerships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDealershipsRow{}
	for rows.Next() {
		var i ListDealershipsRow
		if err := rows.Scan(
			&i.DealershipID,
			&i.Name,
			&i.Code,
			&i.Address,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDealerships = `-- name: UpdateDealerships :execrows
UPDATE appointment_scheduler.dealerships
SET name = $1, code = $2, address = $3, timezone = $4, is_active = $5, updated_at = $6
WHERE dealership_id = $7 AND deleted_at IS NULL
`

type UpdateDealershipsParams struct {
	Name         string
	Code         string
	Address      string
	Timezone     string
	IsActive     bool
	UpdatedAt    time.Time
	DealershipID pgtype.UUID
}

func (q *Queries) UpdateDealerships(ctx context.Context, arg UpdateDealershipsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDealerships,
		arg.Name,
		arg.Code,
		arg.Address,
		arg.Timezone,
		arg.IsActive,
		arg.UpdatedAt,
		arg.DealershipID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
