// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dealership_operation_time.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDealershipOperationTime = `-- name: CreateDealershipOperationTime :exec
INSERT INTO appointment_scheduler.dealership_operation_time (dealership_operation_time_id, dealership_id, day_of_week, opens_at, closes_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateDealershipOperationTimeParams struct {
	DealershipOperationTimeID pgtype.UUID
	DealershipID              pgtype.UUID
	DayOfWeek                 int16
	OpensAt                   pgtype.Time
	ClosesAt                  pgtype.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

func (q *Queries) CreateDealershipOperationTime(ctx context.Context, arg CreateDealershipOperationTimeParams) error {
	_, err := q.db.Exec(ctx, createDealershipOperationTime,
		arg.DealershipOperationTimeID,
		arg.DealershipID,
		arg.DayOfWeek,
		arg.OpensAt,
		arg.ClosesAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDealershipOperationTime = `-- name: DeleteDealershipOperationTime :execrows
UPDATE appointment_scheduler.dealership_operation_time
SET deleted_at = $1::timestamptz
WHERE dealership_operation_time_id = $2 AND deleted_at IS NULL
`

type DeleteDealershipOperationTimeParams struct {
	DeletedAt                 time.Time
	DealershipOperationTimeID pgtype.UUID
}

func (q *Queries) DeleteDealershipOperationTime(ctx context.Context, arg DeleteDealershipOperationTimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDealershipOperationTime, arg.DeletedAt, arg.DealershipOperationTimeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDealershipOperationTime = `-- name: GetDealershipOperationTime :one

SELECT dealership_operation_time_id, dealership_id, day_of_week, opens_at, closes_at, created_at, updated_at, deleted_at
FROM appointment_scheduler.dealership_operation_time
WHERE dealership_operation_time_id = $1 AND deleted_at IS NULL
`

type GetDealershipOperationTimeRow struct {
	DealershipOperationTimeID pgtype.UUID
	DealershipID              pgtype.UUID
	DayOfWeek                 int16
	OpensAt                   pgtype.Time
	ClosesAt                  pgtype.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	DeletedAt                 pgtype.Timestamptz
}

// dealership operation time CRUD queries.
func (q *Queries) GetDealershipOperationTime(ctx context.Context, dealershipOperationTimeID pgtype.UUID) (GetDealershipOperationTimeRow, error) {
	row := q.db.QueryRow(ctx, getDealershipOperationTime, dealershipOperationTimeID)
	var i GetDealershipOperationTimeRow
	err := row.Scan(
		&i.DealershipOperationTimeID,
		&i.DealershipID,
		&i.DayOfWeek,
		&i.OpensAt,
		&i.ClosesAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDealershipOperationTime = `-- name: UpdateDealershipOperationTime :execrows
UPDATE appointment_scheduler.dealership_operation_time
SET dealership_id = $1, day_of_week = $2, opens_at = $3, closes_at = $4, updated_at = $5
WHERE dealership_operation_time_id = $6 AND deleted_at IS NULL
`

type UpdateDealershipOperationTimeParams struct {
	DealershipID              pgtype.UUID
	DayOfWeek                 int16
	OpensAt                   pgtype.Time
	ClosesAt                  pgtype.Time
	UpdatedAt                 time.Time
	DealershipOperationTimeID pgtype.UUID
}

func (q *Queries) UpdateDealershipOperationTime(ctx context.Context, arg UpdateDealershipOperationTimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDealershipOperationTime,
		arg.DealershipID,
		arg.DayOfWeek,
		arg.OpensAt,
		arg.ClosesAt,
		arg.UpdatedAt,
		arg.DealershipOperationTimeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
