// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppointmentSchedulerAppointment struct {
	AppointmentID          pgtype.UUID
	ReferenceCode          string
	CustomerID             pgtype.UUID
	VehicleID              pgtype.UUID
	DealershipID           pgtype.UUID
	ServiceTypeID          pgtype.UUID
	TechnicianID           pgtype.UUID
	ServiceBayID           pgtype.UUID
	StartsAt               time.Time
	EndsAt                 time.Time
	Status                 string
	Notes                  *string
	CreatedByUserID        pgtype.UUID
	CancelledByUserID      pgtype.UUID
	CancellationReason     *string
	CreatedAt              time.Time
	DeletedAt              pgtype.Timestamptz
	UpdatedAt              time.Time
	CancelledAt            pgtype.Timestamptz
	CheckedInAt            pgtype.Timestamptz
	InProgressAt           pgtype.Timestamptz
	StartedAt              pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	ActualEndsAt           pgtype.Timestamptz
	PlannedDurationMinutes *int32
}

type AppointmentSchedulerAppointmentAuditEvent struct {
	AppointmentAuditEventID pgtype.UUID
	AppointmentID           pgtype.UUID
	ActorUserID             pgtype.UUID
	EventType               string
	BeforeData              []byte
	AfterData               []byte
	OccurredAt              time.Time
}

type AppointmentSchedulerAppointmentResourceReservation struct {
	AppointmentResourceReservationID pgtype.UUID
	AppointmentID                    pgtype.UUID
	ResourceType                     string
	ResourceID                       pgtype.UUID
	ReservedStartsAt                 time.Time
	ReservedEndsAt                   time.Time
	Status                           string
	AssignedAt                       time.Time
	ReleasedAt                       pgtype.Timestamptz
	AssignedByUserID                 pgtype.UUID
	Reason                           *string
}

type AppointmentSchedulerBayCapability struct {
	BayCapabilityID pgtype.UUID
	Code            string
	Name            string
	Description     *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AppointmentSchedulerCustomer struct {
	CustomerID pgtype.UUID
	Name       string
	Phone      string
	Email      *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type AppointmentSchedulerCustomerDealership struct {
	CustomerID   pgtype.UUID
	DealershipID pgtype.UUID
	CreatedAt    time.Time
}

type AppointmentSchedulerDealership struct {
	DealershipID pgtype.UUID
	Name         string
	Code         string
	Address      string
	Timezone     string
	IsActive     bool
	CreatedAt    time.Time
	DeletedAt    pgtype.Timestamptz
	UpdatedAt    time.Time
}

type AppointmentSchedulerDealershipOperationTime struct {
	DealershipOperationTimeID pgtype.UUID
	DealershipID              pgtype.UUID
	DayOfWeek                 int16
	OpensAt                   pgtype.Time
	ClosesAt                  pgtype.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type AppointmentSchedulerRole struct {
	RoleID      pgtype.UUID
	Code        string
	Name        string
	Description *string
	CreatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
	UpdatedAt   time.Time
}

type AppointmentSchedulerServiceBay struct {
	ServiceBayID pgtype.UUID
	DealershipID pgtype.UUID
	Code         string
	Name         string
	IsActive     bool
	CreatedAt    time.Time
	DeletedAt    pgtype.Timestamptz
	UpdatedAt    time.Time
}

type AppointmentSchedulerServiceBayCapability struct {
	ServiceBayCapabilityID pgtype.UUID
	ServiceBayID           pgtype.UUID
	BayCapabilityID        pgtype.UUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type AppointmentSchedulerServiceType struct {
	ServiceTypeID          pgtype.UUID
	DealershipID           pgtype.UUID
	Name                   string
	DefaultDurationMinutes int32
	MinDurationMinutes     int32
	MaxDurationMinutes     int32
	IsActive               bool
	CreatedAt              time.Time
	DeletedAt              pgtype.Timestamptz
	UpdatedAt              time.Time
}

type AppointmentSchedulerServiceTypeRequiredBayCapability struct {
	ServiceTypeRequiredBayCapabilityID pgtype.UUID
	ServiceTypeID                      pgtype.UUID
	BayCapabilityID                    pgtype.UUID
	CreatedAt                          time.Time
	UpdatedAt                          time.Time
}

type AppointmentSchedulerServiceTypeRequiredSkill struct {
	ServiceTypeRequiredSkillID pgtype.UUID
	ServiceTypeID              pgtype.UUID
	SkillID                    pgtype.UUID
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

type AppointmentSchedulerSkill struct {
	SkillID   pgtype.UUID
	Code      string
	Name      string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AppointmentSchedulerTechnician struct {
	TechnicianID pgtype.UUID
	UserID       pgtype.UUID
	IsActive     bool
	CreatedAt    time.Time
	DeletedAt    pgtype.Timestamptz
	UpdatedAt    time.Time
}

type AppointmentSchedulerTechnicianShift struct {
	TechnicianShiftID pgtype.UUID
	TechnicianID      pgtype.UUID
	DayOfWeek         int16
	StartsAt          pgtype.Time
	EndsAt            pgtype.Time
	CreatedAt         time.Time
	DeletedAt         pgtype.Timestamptz
	UpdatedAt         time.Time
}

type AppointmentSchedulerTechnicianSkill struct {
	TechnicianSkillID pgtype.UUID
	TechnicianID      pgtype.UUID
	SkillID           pgtype.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type AppointmentSchedulerTechnicianTimeOff struct {
	TechnicianTimeOffID pgtype.UUID
	TechnicianID        pgtype.UUID
	StartsAt            time.Time
	EndsAt              time.Time
	Reason              *string
	CreatedByUserID     pgtype.UUID
	CreatedAt           time.Time
	DeletedAt           pgtype.Timestamptz
	UpdatedAt           time.Time
}

type AppointmentSchedulerUser struct {
	UserID       pgtype.UUID
	AuthUserID   pgtype.UUID
	Name         string
	Phone        *string
	Email        *string
	DealershipID pgtype.UUID
	IsActive     bool
	CreatedAt    time.Time
	DeletedAt    pgtype.Timestamptz
	UpdatedAt    time.Time
}

type AppointmentSchedulerUserRole struct {
	UserRoleID pgtype.UUID
	UserID     pgtype.UUID
	RoleID     pgtype.UUID
	CreatedAt  time.Time
	DeletedAt  pgtype.Timestamptz
}

type AppointmentSchedulerVehicle struct {
	VehicleID         pgtype.UUID
	CustomerID        pgtype.UUID
	Vin               *string
	RegistrationPlate *string
	Make              string
	Model             string
	ModelYear         *int16
	CreatedAt         time.Time
	DeletedAt         pgtype.Timestamptz
	UpdatedAt         time.Time
}
