// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoles = `-- name: CreateRoles :exec
INSERT INTO appointment_scheduler.roles (role_id, code, name, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateRolesParams struct {
	RoleID      pgtype.UUID
	Code        string
	Name        string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateRoles(ctx context.Context, arg CreateRolesParams) error {
	_, err := q.db.Exec(ctx, createRoles,
		arg.RoleID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteRoles = `-- name: DeleteRoles :execrows
UPDATE appointment_scheduler.roles
SET deleted_at = $1::timestamptz
WHERE role_id = $2 AND deleted_at IS NULL
`

type DeleteRolesParams struct {
	DeletedAt time.Time
	RoleID    pgtype.UUID
}

func (q *Queries) DeleteRoles(ctx context.Context, arg DeleteRolesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoles, arg.DeletedAt, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoleByCode = `-- name: GetRoleByCode :one

SELECT role_id, code
FROM appointment_scheduler.roles
WHERE code = $1
  AND deleted_at IS NULL
`

type GetRoleByCodeRow struct {
	RoleID pgtype.UUID
	Code   string
}

// roles CRUD queries.
func (q *Queries) GetRoleByCode(ctx context.Context, code string) (GetRoleByCodeRow, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i GetRoleByCodeRow
	err := row.Scan(&i.RoleID, &i.Code)
	return i, err
}

const getRoles = `-- name: GetRoles :one
SELECT role_id, code, name, description, created_at, updated_at, deleted_at
FROM appointment_scheduler.roles
WHERE role_id = $1 AND deleted_at IS NULL
`

type GetRolesRow struct {
	RoleID      pgtype.UUID
	Code        string
	Name        string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) GetRoles(ctx context.Context, roleID pgtype.UUID) (GetRolesRow, error) {
	row := q.db.QueryRow(ctx, getRoles, roleID)
	var i GetRolesRow
	err := row.Scan(
		&i.RoleID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateRoles = `-- name: UpdateRoles :execrows
UPDATE appointment_scheduler.roles
SET code = $1, name = $2, description = $3, updated_at = $4
WHERE role_id = $5 AND deleted_at IS NULL
`

type UpdateRolesParams struct {
	Code        string
	Name        string
	Description *string
	UpdatedAt   time.Time
	RoleID      pgtype.UUID
}

func (q *Queries) UpdateRoles(ctx context.Context, arg UpdateRolesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRoles,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.RoleID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
