// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_type_required_skills.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceTypeRequiredSkill = `-- name: CreateServiceTypeRequiredSkill :one
INSERT INTO appointment_scheduler.service_type_required_skills (service_type_required_skill_id, service_type_id, skill_id, created_at, updated_at)
SELECT $1, service_types.service_type_id,
  skills.skill_id, $2, $3
FROM appointment_scheduler.service_types
JOIN appointment_scheduler.skills ON skills.skill_id = $4
WHERE service_types.service_type_id = $5
  AND service_types.dealership_id = $6
  AND service_types.deleted_at IS NULL
RETURNING service_type_required_skill_id, service_type_id, skill_id, created_at, updated_at
`

type CreateServiceTypeRequiredSkillParams struct {
	ServiceTypeRequiredSkillID pgtype.UUID
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	SkillID                    pgtype.UUID
	ServiceTypeID              pgtype.UUID
	DealershipID               pgtype.UUID
}

func (q *Queries) CreateServiceTypeRequiredSkill(ctx context.Context, arg CreateServiceTypeRequiredSkillParams) (AppointmentSchedulerServiceTypeRequiredSkill, error) {
	row := q.db.QueryRow(ctx, createServiceTypeRequiredSkill,
		arg.ServiceTypeRequiredSkillID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SkillID,
		arg.ServiceTypeID,
		arg.DealershipID,
	)
	var i AppointmentSchedulerServiceTypeRequiredSkill
	err := row.Scan(
		&i.ServiceTypeRequiredSkillID,
		&i.ServiceTypeID,
		&i.SkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceTypeRequiredSkill = `-- name: DeleteServiceTypeRequiredSkill :execrows
DELETE FROM appointment_scheduler.service_type_required_skills required_skill
USING appointment_scheduler.service_types service_types
WHERE required_skill.service_type_required_skill_id = $1
  AND required_skill.service_type_id = $2
  AND service_types.service_type_id = required_skill.service_type_id
  AND service_types.dealership_id = $3
  AND service_types.deleted_at IS NULL
`

type DeleteServiceTypeRequiredSkillParams struct {
	ServiceTypeRequiredSkillID pgtype.UUID
	ServiceTypeID              pgtype.UUID
	DealershipID               pgtype.UUID
}

func (q *Queries) DeleteServiceTypeRequiredSkill(ctx context.Context, arg DeleteServiceTypeRequiredSkillParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceTypeRequiredSkill, arg.ServiceTypeRequiredSkillID, arg.ServiceTypeID, arg.DealershipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServiceTypeRequiredSkill = `-- name: GetServiceTypeRequiredSkill :one
SELECT required_skill.service_type_required_skill_id, required_skill.service_type_id,
  skills.skill_id, skills.code, skills.name, required_skill.created_at, required_skill.updated_at
FROM appointment_scheduler.service_type_required_skills required_skill
JOIN appointment_scheduler.service_types service_types ON service_types.service_type_id = required_skill.service_type_id
JOIN appointment_scheduler.skills skills ON skills.skill_id = required_skill.skill_id
WHERE required_skill.service_type_required_skill_id = $1
  AND required_skill.service_type_id = $2
  AND service_types.dealership_id = $3
  AND service_types.deleted_at IS NULL
`

type GetServiceTypeRequiredSkillParams struct {
	ServiceTypeRequiredSkillID pgtype.UUID
	ServiceTypeID              pgtype.UUID
	DealershipID               pgtype.UUID
}

type GetServiceTypeRequiredSkillRow struct {
	ServiceTypeRequiredSkillID pgtype.UUID
	ServiceTypeID              pgtype.UUID
	SkillID                    pgtype.UUID
	Code                       string
	Name                       string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

func (q *Queries) GetServiceTypeRequiredSkill(ctx context.Context, arg GetServiceTypeRequiredSkillParams) (GetServiceTypeRequiredSkillRow, error) {
	row := q.db.QueryRow(ctx, getServiceTypeRequiredSkill, arg.ServiceTypeRequiredSkillID, arg.ServiceTypeID, arg.DealershipID)
	var i GetServiceTypeRequiredSkillRow
	err := row.Scan(
		&i.ServiceTypeRequiredSkillID,
		&i.ServiceTypeID,
		&i.SkillID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceTypeRequiredSkills = `-- name: ListServiceTypeRequiredSkills :many
SELECT required_skill.service_type_required_skill_id, required_skill.service_type_id,
  skills.skill_id, skills.code, skills.name, required_skill.created_at, required_skill.updated_at
FROM appointment_scheduler.service_type_required_skills required_skill
JOIN appointment_scheduler.service_types service_types ON service_types.service_type_id = required_skill.service_type_id
JOIN appointment_scheduler.skills skills ON skills.skill_id = required_skill.skill_id
WHERE required_skill.service_type_id = $1
  AND service_types.dealership_id = $2
  AND service_types.deleted_at IS NULL
ORDER BY skills.name, skills.skill_id
`

type ListServiceTypeRequiredSkillsParams struct {
	ServiceTypeID pgtype.UUID
	DealershipID  pgtype.UUID
}

type ListServiceTypeRequiredSkillsRow struct {
	ServiceTypeRequiredSkillID pgtype.UUID
	ServiceTypeID              pgtype.UUID
	SkillID                    pgtype.UUID
	Code                       string
	Name                       string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

func (q *Queries) ListServiceTypeRequiredSkills(ctx context.Context, arg ListServiceTypeRequiredSkillsParams) ([]ListServiceTypeRequiredSkillsRow, error) {
	rows, err := q.db.Query(ctx, listServiceTypeRequiredSkills, arg.ServiceTypeID, arg.DealershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceTypeRequiredSkillsRow{}
	for rows.Next() {
		var i ListServiceTypeRequiredSkillsRow
		if err := rows.Scan(
			&i.ServiceTypeRequiredSkillID,
			&i.ServiceTypeID,
			&i.SkillID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skillExists = `-- name: SkillExists :one

SELECT EXISTS(
  SELECT 1
  FROM appointment_scheduler.skills
  WHERE skill_id = $1
)
`

// Required skills are always selected through their dealership-owned service type.
func (q *Queries) SkillExists(ctx context.Context, skillID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, skillExists, skillID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateServiceTypeRequiredSkill = `-- name: UpdateServiceTypeRequiredSkill :one
UPDATE appointment_scheduler.service_type_required_skills required_skill
SET skill_id = $1, updated_at = $2
FROM appointment_scheduler.service_types service_types
WHERE required_skill.service_type_required_skill_id = $3
  AND required_skill.service_type_id = $4
  AND service_types.service_type_id = required_skill.service_type_id
  AND service_types.dealership_id = $5
  AND service_types.deleted_at IS NULL
RETURNING required_skill.service_type_required_skill_id, required_skill.service_type_id,
  required_skill.skill_id, required_skill.created_at, required_skill.updated_at
`

type UpdateServiceTypeRequiredSkillParams struct {
	SkillID                    pgtype.UUID
	UpdatedAt                  time.Time
	ServiceTypeRequiredSkillID pgtype.UUID
	ServiceTypeID              pgtype.UUID
	DealershipID               pgtype.UUID
}

func (q *Queries) UpdateServiceTypeRequiredSkill(ctx context.Context, arg UpdateServiceTypeRequiredSkillParams) (AppointmentSchedulerServiceTypeRequiredSkill, error) {
	row := q.db.QueryRow(ctx, updateServiceTypeRequiredSkill,
		arg.SkillID,
		arg.UpdatedAt,
		arg.ServiceTypeRequiredSkillID,
		arg.ServiceTypeID,
		arg.DealershipID,
	)
	var i AppointmentSchedulerServiceTypeRequiredSkill
	err := row.Scan(
		&i.ServiceTypeRequiredSkillID,
		&i.ServiceTypeID,
		&i.SkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
