// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_types.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceTypes = `-- name: CreateServiceTypes :exec
INSERT INTO appointment_scheduler.service_types (service_type_id, dealership_id, name, default_duration_minutes, min_duration_minutes, max_duration_minutes, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateServiceTypesParams struct {
	ServiceTypeID          pgtype.UUID
	DealershipID           pgtype.UUID
	Name                   string
	DefaultDurationMinutes int32
	MinDurationMinutes     int32
	MaxDurationMinutes     int32
	IsActive               bool
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) CreateServiceTypes(ctx context.Context, arg CreateServiceTypesParams) error {
	_, err := q.db.Exec(ctx, createServiceTypes,
		arg.ServiceTypeID,
		arg.DealershipID,
		arg.Name,
		arg.DefaultDurationMinutes,
		arg.MinDurationMinutes,
		arg.MaxDurationMinutes,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteServiceTypes = `-- name: DeleteServiceTypes :execrows
UPDATE appointment_scheduler.service_types
SET deleted_at = $1::timestamptz
WHERE service_type_id = $2
  AND dealership_id = $3
  AND deleted_at IS NULL
`

type DeleteServiceTypesParams struct {
	DeletedAt     time.Time
	ServiceTypeID pgtype.UUID
	DealershipID  pgtype.UUID
}

func (q *Queries) DeleteServiceTypes(ctx context.Context, arg DeleteServiceTypesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceTypes, arg.DeletedAt, arg.ServiceTypeID, arg.DealershipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServiceType = `-- name: GetServiceType :one

SELECT service_type_id, dealership_id, name, default_duration_minutes, min_duration_minutes, max_duration_minutes, is_active, created_at, updated_at
FROM appointment_scheduler.service_types
WHERE service_type_id = $1
  AND dealership_id = $2
  AND deleted_at IS NULL
`

type GetServiceTypeParams struct {
	ServiceTypeID pgtype.UUID
	DealershipID  pgtype.UUID
}

type GetServiceTypeRow struct {
	ServiceTypeID          pgtype.UUID
	DealershipID           pgtype.UUID
	Name                   string
	DefaultDurationMinutes int32
	MinDurationMinutes     int32
	MaxDurationMinutes     int32
	IsActive               bool
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

// service types CRUD queries.
func (q *Queries) GetServiceType(ctx context.Context, arg GetServiceTypeParams) (GetServiceTypeRow, error) {
	row := q.db.QueryRow(ctx, getServiceType, arg.ServiceTypeID, arg.DealershipID)
	var i GetServiceTypeRow
	err := row.Scan(
		&i.ServiceTypeID,
		&i.DealershipID,
		&i.Name,
		&i.DefaultDurationMinutes,
		&i.MinDurationMinutes,
		&i.MaxDurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasAppointmentsForServiceType = `-- name: HasAppointmentsForServiceType :one
SELECT EXISTS(
  SELECT 1
  FROM appointment_scheduler.appointments
  WHERE service_type_id = $1
)
`

func (q *Queries) HasAppointmentsForServiceType(ctx context.Context, serviceTypeID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasAppointmentsForServiceType, serviceTypeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listServiceTypes = `-- name: ListServiceTypes :many
SELECT service_type_id, dealership_id, name, default_duration_minutes, min_duration_minutes, max_duration_minutes, is_active, created_at, updated_at
FROM appointment_scheduler.service_types
WHERE dealership_id = $1 AND deleted_at IS NULL
ORDER BY name, service_type_id
`

type ListServiceTypesRow struct {
	ServiceTypeID          pgtype.UUID
	DealershipID           pgtype.UUID
	Name                   string
	DefaultDurationMinutes int32
	MinDurationMinutes     int32
	MaxDurationMinutes     int32
	IsActive               bool
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) ListServiceTypes(ctx context.Context, dealershipID pgtype.UUID) ([]ListServiceTypesRow, error) {
	rows, err := q.db.Query(ctx, listServiceTypes, dealershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceTypesRow{}
	for rows.Next() {
		var i ListServiceTypesRow
		if err := rows.Scan(
			&i.ServiceTypeID,
			&i.DealershipID,
			&i.Name,
			&i.DefaultDurationMinutes,
			&i.MinDurationMinutes,
			&i.MaxDurationMinutes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceTypes = `-- name: UpdateServiceTypes :execrows
UPDATE appointment_scheduler.service_types
SET name = $1, default_duration_minutes = $2, min_duration_minutes = $3, max_duration_minutes = $4, is_active = $5, updated_at = $6
WHERE service_type_id = $7
  AND dealership_id = $8
  AND deleted_at IS NULL
`

type UpdateServiceTypesParams struct {
	Name                   string
	DefaultDurationMinutes int32
	MinDurationMinutes     int32
	MaxDurationMinutes     int32
	IsActive               bool
	UpdatedAt              time.Time
	ServiceTypeID          pgtype.UUID
	DealershipID           pgtype.UUID
}

func (q *Queries) UpdateServiceTypes(ctx context.Context, arg UpdateServiceTypesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateServiceTypes,
		arg.Name,
		arg.DefaultDurationMinutes,
		arg.MinDurationMinutes,
		arg.MaxDurationMinutes,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ServiceTypeID,
		arg.DealershipID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
