// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_bay_capabilities.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceBayCapabilities = `-- name: CreateServiceBayCapabilities :exec
INSERT INTO appointment_scheduler.service_bay_capabilities (service_bay_capability_id, service_bay_id, capability_code, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateServiceBayCapabilitiesParams struct {
	ServiceBayCapabilityID pgtype.UUID
	ServiceBayID           pgtype.UUID
	CapabilityCode         string
	CreatedAt              time.Time
}

func (q *Queries) CreateServiceBayCapabilities(ctx context.Context, arg CreateServiceBayCapabilitiesParams) error {
	_, err := q.db.Exec(ctx, createServiceBayCapabilities,
		arg.ServiceBayCapabilityID,
		arg.ServiceBayID,
		arg.CapabilityCode,
		arg.CreatedAt,
	)
	return err
}

const deleteServiceBayCapabilities = `-- name: DeleteServiceBayCapabilities :execrows
UPDATE appointment_scheduler.service_bay_capabilities
SET deleted_at = $1::timestamptz
WHERE service_bay_capability_id = $2 AND deleted_at IS NULL
`

type DeleteServiceBayCapabilitiesParams struct {
	DeletedAt              time.Time
	ServiceBayCapabilityID pgtype.UUID
}

func (q *Queries) DeleteServiceBayCapabilities(ctx context.Context, arg DeleteServiceBayCapabilitiesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceBayCapabilities, arg.DeletedAt, arg.ServiceBayCapabilityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServiceBayCapabilities = `-- name: GetServiceBayCapabilities :one

SELECT service_bay_capability_id, service_bay_id, capability_code, created_at, deleted_at
FROM appointment_scheduler.service_bay_capabilities
WHERE service_bay_capability_id = $1 AND deleted_at IS NULL
`

// service bay capabilities CRUD queries.
func (q *Queries) GetServiceBayCapabilities(ctx context.Context, serviceBayCapabilityID pgtype.UUID) (AppointmentSchedulerServiceBayCapability, error) {
	row := q.db.QueryRow(ctx, getServiceBayCapabilities, serviceBayCapabilityID)
	var i AppointmentSchedulerServiceBayCapability
	err := row.Scan(
		&i.ServiceBayCapabilityID,
		&i.ServiceBayID,
		&i.CapabilityCode,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateServiceBayCapabilities = `-- name: UpdateServiceBayCapabilities :execrows
UPDATE appointment_scheduler.service_bay_capabilities
SET service_bay_id = $1, capability_code = $2
WHERE service_bay_capability_id = $3 AND deleted_at IS NULL
`

type UpdateServiceBayCapabilitiesParams struct {
	ServiceBayID           pgtype.UUID
	CapabilityCode         string
	ServiceBayCapabilityID pgtype.UUID
}

func (q *Queries) UpdateServiceBayCapabilities(ctx context.Context, arg UpdateServiceBayCapabilitiesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateServiceBayCapabilities, arg.ServiceBayID, arg.CapabilityCode, arg.ServiceBayCapabilityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
