// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_bays.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const canReadAvailableServiceBays = `-- name: CanReadAvailableServiceBays :one

SELECT EXISTS (
  SELECT 1
  FROM appointment_scheduler.users AS users
  JOIN appointment_scheduler.user_roles AS user_roles ON user_roles.user_id = users.user_id
  JOIN appointment_scheduler.roles AS roles ON roles.role_id = user_roles.role_id
  WHERE users.auth_user_id = $1
    AND users.dealership_id = $2
    AND users.is_active
    AND users.deleted_at IS NULL
    AND user_roles.deleted_at IS NULL
    AND roles.deleted_at IS NULL
    AND roles.code IN ('admin', 'staff', 'dealer')
)
`

type CanReadAvailableServiceBaysParams struct {
	AuthUserID   pgtype.UUID
	DealershipID pgtype.UUID
}

// service bays CRUD queries.
func (q *Queries) CanReadAvailableServiceBays(ctx context.Context, arg CanReadAvailableServiceBaysParams) (bool, error) {
	row := q.db.QueryRow(ctx, canReadAvailableServiceBays, arg.AuthUserID, arg.DealershipID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createServiceBay = `-- name: CreateServiceBay :exec
INSERT INTO appointment_scheduler.service_bays (service_bay_id, dealership_id, code, name, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateServiceBayParams struct {
	ServiceBayID pgtype.UUID
	DealershipID pgtype.UUID
	Code         string
	Name         string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateServiceBay(ctx context.Context, arg CreateServiceBayParams) error {
	_, err := q.db.Exec(ctx, createServiceBay,
		arg.ServiceBayID,
		arg.DealershipID,
		arg.Code,
		arg.Name,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteServiceBay = `-- name: DeleteServiceBay :execrows
UPDATE appointment_scheduler.service_bays
SET deleted_at = $1::timestamptz
WHERE service_bay_id = $2
  AND dealership_id = $3
  AND deleted_at IS NULL
`

type DeleteServiceBayParams struct {
	DeletedAt    time.Time
	ServiceBayID pgtype.UUID
	DealershipID pgtype.UUID
}

func (q *Queries) DeleteServiceBay(ctx context.Context, arg DeleteServiceBayParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceBay, arg.DeletedAt, arg.ServiceBayID, arg.DealershipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServiceBay = `-- name: GetServiceBay :one
SELECT service_bay_id, dealership_id, code, name, is_active, created_at, updated_at
FROM appointment_scheduler.service_bays
WHERE service_bay_id = $1
  AND dealership_id = $2
  AND deleted_at IS NULL
`

type GetServiceBayParams struct {
	ServiceBayID pgtype.UUID
	DealershipID pgtype.UUID
}

type GetServiceBayRow struct {
	ServiceBayID pgtype.UUID
	DealershipID pgtype.UUID
	Code         string
	Name         string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetServiceBay(ctx context.Context, arg GetServiceBayParams) (GetServiceBayRow, error) {
	row := q.db.QueryRow(ctx, getServiceBay, arg.ServiceBayID, arg.DealershipID)
	var i GetServiceBayRow
	err := row.Scan(
		&i.ServiceBayID,
		&i.DealershipID,
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasAppointmentsForServiceBay = `-- name: HasAppointmentsForServiceBay :one
SELECT EXISTS(
  SELECT 1
  FROM appointment_scheduler.appointments
  WHERE service_bay_id = $1
    AND deleted_at IS NULL
)
`

func (q *Queries) HasAppointmentsForServiceBay(ctx context.Context, serviceBayID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasAppointmentsForServiceBay, serviceBayID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAvailableServiceBays = `-- name: ListAvailableServiceBays :many
SELECT service_bay_id, dealership_id, code, name, is_active, created_at, updated_at
FROM appointment_scheduler.service_bays AS service_bays
WHERE service_bays.dealership_id = $1
  AND is_active
  AND deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM appointment_scheduler.appointments AS appointments
    WHERE appointments.service_bay_id = service_bays.service_bay_id
      AND appointments.deleted_at IS NULL
      AND appointments.status IN ('requested', 'checked_in', 'in_progress')
      AND appointments.starts_at < $2
      AND appointments.ends_at > $3
  )
ORDER BY code, service_bay_id
`

type ListAvailableServiceBaysParams struct {
	DealershipID pgtype.UUID
	EndsAt       time.Time
	StartsAt     time.Time
}

type ListAvailableServiceBaysRow struct {
	ServiceBayID pgtype.UUID
	DealershipID pgtype.UUID
	Code         string
	Name         string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ListAvailableServiceBays(ctx context.Context, arg ListAvailableServiceBaysParams) ([]ListAvailableServiceBaysRow, error) {
	rows, err := q.db.Query(ctx, listAvailableServiceBays, arg.DealershipID, arg.EndsAt, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableServiceBaysRow{}
	for rows.Next() {
		var i ListAvailableServiceBaysRow
		if err := rows.Scan(
			&i.ServiceBayID,
			&i.DealershipID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceBays = `-- name: ListServiceBays :many
SELECT service_bay_id, dealership_id, code, name, is_active, created_at, updated_at
FROM appointment_scheduler.service_bays
WHERE dealership_id = $1
  AND deleted_at IS NULL
  AND ($2::boolean IS NULL OR is_active = $2::boolean)
ORDER BY code, service_bay_id
LIMIT $4 OFFSET $3
`

type ListServiceBaysParams struct {
	DealershipID pgtype.UUID
	IsActive     *bool
	OffsetCount  int32
	LimitCount   int32
}

type ListServiceBaysRow struct {
	ServiceBayID pgtype.UUID
	DealershipID pgtype.UUID
	Code         string
	Name         string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ListServiceBays(ctx context.Context, arg ListServiceBaysParams) ([]ListServiceBaysRow, error) {
	rows, err := q.db.Query(ctx, listServiceBays,
		arg.DealershipID,
		arg.IsActive,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceBaysRow{}
	for rows.Next() {
		var i ListServiceBaysRow
		if err := rows.Scan(
			&i.ServiceBayID,
			&i.DealershipID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceBay = `-- name: UpdateServiceBay :execrows
UPDATE appointment_scheduler.service_bays
SET code = $1, name = $2, is_active = $3, updated_at = $4
WHERE service_bay_id = $5
  AND dealership_id = $6
  AND deleted_at IS NULL
`

type UpdateServiceBayParams struct {
	Code         string
	Name         string
	IsActive     bool
	UpdatedAt    time.Time
	ServiceBayID pgtype.UUID
	DealershipID pgtype.UUID
}

func (q *Queries) UpdateServiceBay(ctx context.Context, arg UpdateServiceBayParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateServiceBay,
		arg.Code,
		arg.Name,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ServiceBayID,
		arg.DealershipID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
