// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_type_required_bay_capabilities.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceTypeRequiredBayCapabilities = `-- name: CreateServiceTypeRequiredBayCapabilities :exec
INSERT INTO appointment_scheduler.service_type_required_bay_capabilities (service_type_required_bay_capability_id, service_type_id, capability_code, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateServiceTypeRequiredBayCapabilitiesParams struct {
	ServiceTypeRequiredBayCapabilityID pgtype.UUID
	ServiceTypeID                      pgtype.UUID
	CapabilityCode                     string
	CreatedAt                          time.Time
}

func (q *Queries) CreateServiceTypeRequiredBayCapabilities(ctx context.Context, arg CreateServiceTypeRequiredBayCapabilitiesParams) error {
	_, err := q.db.Exec(ctx, createServiceTypeRequiredBayCapabilities,
		arg.ServiceTypeRequiredBayCapabilityID,
		arg.ServiceTypeID,
		arg.CapabilityCode,
		arg.CreatedAt,
	)
	return err
}

const deleteServiceTypeRequiredBayCapabilities = `-- name: DeleteServiceTypeRequiredBayCapabilities :execrows
UPDATE appointment_scheduler.service_type_required_bay_capabilities
SET deleted_at = $1::timestamptz
WHERE service_type_required_bay_capability_id = $2 AND deleted_at IS NULL
`

type DeleteServiceTypeRequiredBayCapabilitiesParams struct {
	DeletedAt                          time.Time
	ServiceTypeRequiredBayCapabilityID pgtype.UUID
}

func (q *Queries) DeleteServiceTypeRequiredBayCapabilities(ctx context.Context, arg DeleteServiceTypeRequiredBayCapabilitiesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceTypeRequiredBayCapabilities, arg.DeletedAt, arg.ServiceTypeRequiredBayCapabilityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServiceTypeRequiredBayCapabilities = `-- name: GetServiceTypeRequiredBayCapabilities :one

SELECT service_type_required_bay_capability_id, service_type_id, capability_code, created_at, deleted_at
FROM appointment_scheduler.service_type_required_bay_capabilities
WHERE service_type_required_bay_capability_id = $1 AND deleted_at IS NULL
`

// service type required bay capabilities CRUD queries.
func (q *Queries) GetServiceTypeRequiredBayCapabilities(ctx context.Context, serviceTypeRequiredBayCapabilityID pgtype.UUID) (AppointmentSchedulerServiceTypeRequiredBayCapability, error) {
	row := q.db.QueryRow(ctx, getServiceTypeRequiredBayCapabilities, serviceTypeRequiredBayCapabilityID)
	var i AppointmentSchedulerServiceTypeRequiredBayCapability
	err := row.Scan(
		&i.ServiceTypeRequiredBayCapabilityID,
		&i.ServiceTypeID,
		&i.CapabilityCode,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateServiceTypeRequiredBayCapabilities = `-- name: UpdateServiceTypeRequiredBayCapabilities :execrows
UPDATE appointment_scheduler.service_type_required_bay_capabilities
SET service_type_id = $1, capability_code = $2
WHERE service_type_required_bay_capability_id = $3 AND deleted_at IS NULL
`

type UpdateServiceTypeRequiredBayCapabilitiesParams struct {
	ServiceTypeID                      pgtype.UUID
	CapabilityCode                     string
	ServiceTypeRequiredBayCapabilityID pgtype.UUID
}

func (q *Queries) UpdateServiceTypeRequiredBayCapabilities(ctx context.Context, arg UpdateServiceTypeRequiredBayCapabilitiesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateServiceTypeRequiredBayCapabilities, arg.ServiceTypeID, arg.CapabilityCode, arg.ServiceTypeRequiredBayCapabilityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
