// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: technician_schedules.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const canReadTechnicianSchedules = `-- name: CanReadTechnicianSchedules :one

SELECT EXISTS (
  SELECT 1
  FROM appointment_scheduler.users AS users
  JOIN appointment_scheduler.user_roles AS user_roles ON user_roles.user_id = users.user_id
  JOIN appointment_scheduler.roles AS roles ON roles.role_id = user_roles.role_id
  WHERE users.auth_user_id = $1
    AND users.dealership_id = $2
    AND users.is_active
    AND users.deleted_at IS NULL
    AND user_roles.deleted_at IS NULL
    AND roles.deleted_at IS NULL
    AND roles.code IN ('admin', 'staff', 'dealer')
)
`

type CanReadTechnicianSchedulesParams struct {
	AuthUserID   pgtype.UUID
	DealershipID pgtype.UUID
}

// Read-side queries for the dealership technician calendar.
func (q *Queries) CanReadTechnicianSchedules(ctx context.Context, arg CanReadTechnicianSchedulesParams) (bool, error) {
	row := q.db.QueryRow(ctx, canReadTechnicianSchedules, arg.AuthUserID, arg.DealershipID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getActiveTechnicianScheduleDealership = `-- name: GetActiveTechnicianScheduleDealership :one
SELECT dealership_id, timezone
FROM appointment_scheduler.dealerships
WHERE dealership_id = $1
  AND is_active
  AND deleted_at IS NULL
`

type GetActiveTechnicianScheduleDealershipRow struct {
	DealershipID pgtype.UUID
	Timezone     string
}

func (q *Queries) GetActiveTechnicianScheduleDealership(ctx context.Context, dealershipID pgtype.UUID) (GetActiveTechnicianScheduleDealershipRow, error) {
	row := q.db.QueryRow(ctx, getActiveTechnicianScheduleDealership, dealershipID)
	var i GetActiveTechnicianScheduleDealershipRow
	err := row.Scan(&i.DealershipID, &i.Timezone)
	return i, err
}

const listActiveTechniciansForSchedule = `-- name: ListActiveTechniciansForSchedule :many
SELECT technicians.technician_id, technicians.user_id, users.name
FROM appointment_scheduler.technicians AS technicians
JOIN appointment_scheduler.users AS users ON users.user_id = technicians.user_id
WHERE users.dealership_id = $1
  AND technicians.is_active
  AND technicians.deleted_at IS NULL
  AND users.deleted_at IS NULL
  AND ($2::uuid IS NULL OR technicians.technician_id = $2::uuid)
ORDER BY technicians.created_at, technicians.technician_id
`

type ListActiveTechniciansForScheduleParams struct {
	DealershipID pgtype.UUID
	TechnicianID pgtype.UUID
}

type ListActiveTechniciansForScheduleRow struct {
	TechnicianID pgtype.UUID
	UserID       pgtype.UUID
	Name         string
}

func (q *Queries) ListActiveTechniciansForSchedule(ctx context.Context, arg ListActiveTechniciansForScheduleParams) ([]ListActiveTechniciansForScheduleRow, error) {
	rows, err := q.db.Query(ctx, listActiveTechniciansForSchedule, arg.DealershipID, arg.TechnicianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTechniciansForScheduleRow{}
	for rows.Next() {
		var i ListActiveTechniciansForScheduleRow
		if err := rows.Scan(&i.TechnicianID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTechnicianScheduleAppointments = `-- name: ListTechnicianScheduleAppointments :many
SELECT appointments.technician_id, appointments.appointment_id, appointments.reference_code,
  appointments.starts_at, appointments.ends_at, appointments.status, service_types.name AS service_type_name,
  service_bays.service_bay_id, service_bays.code AS service_bay_code
FROM appointment_scheduler.appointments AS appointments
JOIN appointment_scheduler.technicians AS technicians ON technicians.technician_id = appointments.technician_id
JOIN appointment_scheduler.users AS users ON users.user_id = technicians.user_id
JOIN appointment_scheduler.service_types AS service_types ON service_types.service_type_id = appointments.service_type_id
JOIN appointment_scheduler.service_bays AS service_bays ON service_bays.service_bay_id = appointments.service_bay_id
WHERE appointments.dealership_id = $1
  AND users.dealership_id = $1
  AND technicians.is_active
  AND technicians.deleted_at IS NULL
  AND users.deleted_at IS NULL
  AND appointments.deleted_at IS NULL
  AND appointments.status IN ('requested', 'checked_in', 'in_progress')
  AND appointments.starts_at < $2
  AND appointments.ends_at > $3
  AND ($4::uuid IS NULL OR appointments.technician_id = $4::uuid)
ORDER BY appointments.technician_id, appointments.starts_at, appointments.ends_at, appointments.appointment_id
`

type ListTechnicianScheduleAppointmentsParams struct {
	DealershipID   pgtype.UUID
	PeriodEndsAt   time.Time
	PeriodStartsAt time.Time
	TechnicianID   pgtype.UUID
}

type ListTechnicianScheduleAppointmentsRow struct {
	TechnicianID    pgtype.UUID
	AppointmentID   pgtype.UUID
	ReferenceCode   string
	StartsAt        time.Time
	EndsAt          time.Time
	Status          string
	ServiceTypeName string
	ServiceBayID    pgtype.UUID
	ServiceBayCode  string
}

func (q *Queries) ListTechnicianScheduleAppointments(ctx context.Context, arg ListTechnicianScheduleAppointmentsParams) ([]ListTechnicianScheduleAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listTechnicianScheduleAppointments,
		arg.DealershipID,
		arg.PeriodEndsAt,
		arg.PeriodStartsAt,
		arg.TechnicianID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTechnicianScheduleAppointmentsRow{}
	for rows.Next() {
		var i ListTechnicianScheduleAppointmentsRow
		if err := rows.Scan(
			&i.TechnicianID,
			&i.AppointmentID,
			&i.ReferenceCode,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.ServiceTypeName,
			&i.ServiceBayID,
			&i.ServiceBayCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTechnicianScheduleShifts = `-- name: ListTechnicianScheduleShifts :many
SELECT shifts.technician_id, shifts.starts_at, shifts.ends_at
FROM appointment_scheduler.technician_shifts AS shifts
JOIN appointment_scheduler.technicians AS technicians ON technicians.technician_id = shifts.technician_id
JOIN appointment_scheduler.users AS users ON users.user_id = technicians.user_id
WHERE users.dealership_id = $1
  AND technicians.is_active
  AND technicians.deleted_at IS NULL
  AND users.deleted_at IS NULL
  AND shifts.deleted_at IS NULL
  AND shifts.day_of_week = $2
  AND ($3::uuid IS NULL OR shifts.technician_id = $3::uuid)
ORDER BY shifts.technician_id, shifts.starts_at, shifts.ends_at
`

type ListTechnicianScheduleShiftsParams struct {
	DealershipID pgtype.UUID
	DayOfWeek    int16
	TechnicianID pgtype.UUID
}

type ListTechnicianScheduleShiftsRow struct {
	TechnicianID pgtype.UUID
	StartsAt     pgtype.Time
	EndsAt       pgtype.Time
}

func (q *Queries) ListTechnicianScheduleShifts(ctx context.Context, arg ListTechnicianScheduleShiftsParams) ([]ListTechnicianScheduleShiftsRow, error) {
	rows, err := q.db.Query(ctx, listTechnicianScheduleShifts, arg.DealershipID, arg.DayOfWeek, arg.TechnicianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTechnicianScheduleShiftsRow{}
	for rows.Next() {
		var i ListTechnicianScheduleShiftsRow
		if err := rows.Scan(&i.TechnicianID, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTechnicianScheduleTimeOff = `-- name: ListTechnicianScheduleTimeOff :many
SELECT time_off.technician_id, time_off.starts_at, time_off.ends_at
FROM appointment_scheduler.technician_time_off AS time_off
JOIN appointment_scheduler.technicians AS technicians ON technicians.technician_id = time_off.technician_id
JOIN appointment_scheduler.users AS users ON users.user_id = technicians.user_id
WHERE users.dealership_id = $1
  AND technicians.is_active
  AND technicians.deleted_at IS NULL
  AND users.deleted_at IS NULL
  AND time_off.deleted_at IS NULL
  AND time_off.starts_at < $2
  AND time_off.ends_at > $3
  AND ($4::uuid IS NULL OR time_off.technician_id = $4::uuid)
ORDER BY time_off.technician_id, time_off.starts_at, time_off.ends_at, time_off.technician_time_off_id
`

type ListTechnicianScheduleTimeOffParams struct {
	DealershipID   pgtype.UUID
	PeriodEndsAt   time.Time
	PeriodStartsAt time.Time
	TechnicianID   pgtype.UUID
}

type ListTechnicianScheduleTimeOffRow struct {
	TechnicianID pgtype.UUID
	StartsAt     time.Time
	EndsAt       time.Time
}

func (q *Queries) ListTechnicianScheduleTimeOff(ctx context.Context, arg ListTechnicianScheduleTimeOffParams) ([]ListTechnicianScheduleTimeOffRow, error) {
	rows, err := q.db.Query(ctx, listTechnicianScheduleTimeOff,
		arg.DealershipID,
		arg.PeriodEndsAt,
		arg.PeriodStartsAt,
		arg.TechnicianID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTechnicianScheduleTimeOffRow{}
	for rows.Next() {
		var i ListTechnicianScheduleTimeOffRow
		if err := rows.Scan(&i.TechnicianID, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
