// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: technician_skills.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTechnicianSkills = `-- name: CreateTechnicianSkills :exec
INSERT INTO appointment_scheduler.technician_skills (technician_skill_id, technician_id, skill_code, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateTechnicianSkillsParams struct {
	TechnicianSkillID pgtype.UUID
	TechnicianID      pgtype.UUID
	SkillCode         string
	ExpiresAt         pgtype.Timestamptz
	CreatedAt         time.Time
}

func (q *Queries) CreateTechnicianSkills(ctx context.Context, arg CreateTechnicianSkillsParams) error {
	_, err := q.db.Exec(ctx, createTechnicianSkills,
		arg.TechnicianSkillID,
		arg.TechnicianID,
		arg.SkillCode,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteTechnicianSkills = `-- name: DeleteTechnicianSkills :execrows
UPDATE appointment_scheduler.technician_skills
SET deleted_at = $1::timestamptz
WHERE technician_skill_id = $2 AND deleted_at IS NULL
`

type DeleteTechnicianSkillsParams struct {
	DeletedAt         time.Time
	TechnicianSkillID pgtype.UUID
}

func (q *Queries) DeleteTechnicianSkills(ctx context.Context, arg DeleteTechnicianSkillsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTechnicianSkills, arg.DeletedAt, arg.TechnicianSkillID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTechnicianSkills = `-- name: GetTechnicianSkills :one

SELECT technician_skill_id, technician_id, skill_code, expires_at, created_at, deleted_at
FROM appointment_scheduler.technician_skills
WHERE technician_skill_id = $1 AND deleted_at IS NULL
`

// technician skills CRUD queries.
func (q *Queries) GetTechnicianSkills(ctx context.Context, technicianSkillID pgtype.UUID) (AppointmentSchedulerTechnicianSkill, error) {
	row := q.db.QueryRow(ctx, getTechnicianSkills, technicianSkillID)
	var i AppointmentSchedulerTechnicianSkill
	err := row.Scan(
		&i.TechnicianSkillID,
		&i.TechnicianID,
		&i.SkillCode,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTechnicianSkills = `-- name: UpdateTechnicianSkills :execrows
UPDATE appointment_scheduler.technician_skills
SET technician_id = $1, skill_code = $2, expires_at = $3
WHERE technician_skill_id = $4 AND deleted_at IS NULL
`

type UpdateTechnicianSkillsParams struct {
	TechnicianID      pgtype.UUID
	SkillCode         string
	ExpiresAt         pgtype.Timestamptz
	TechnicianSkillID pgtype.UUID
}

func (q *Queries) UpdateTechnicianSkills(ctx context.Context, arg UpdateTechnicianSkillsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTechnicianSkills,
		arg.TechnicianID,
		arg.SkillCode,
		arg.ExpiresAt,
		arg.TechnicianSkillID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
