// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: technician_time_off.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTechnicianTimeOff = `-- name: CreateTechnicianTimeOff :exec
INSERT INTO appointment_scheduler.technician_time_off (technician_time_off_id, technician_id, starts_at, ends_at, reason, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTechnicianTimeOffParams struct {
	TechnicianTimeOffID pgtype.UUID
	TechnicianID        pgtype.UUID
	StartsAt            time.Time
	EndsAt              time.Time
	Reason              *string
	CreatedAt           time.Time
}

func (q *Queries) CreateTechnicianTimeOff(ctx context.Context, arg CreateTechnicianTimeOffParams) error {
	_, err := q.db.Exec(ctx, createTechnicianTimeOff,
		arg.TechnicianTimeOffID,
		arg.TechnicianID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const deleteTechnicianTimeOff = `-- name: DeleteTechnicianTimeOff :execrows
UPDATE appointment_scheduler.technician_time_off
SET deleted_at = $1::timestamptz
WHERE technician_time_off_id = $2 AND deleted_at IS NULL
`

type DeleteTechnicianTimeOffParams struct {
	DeletedAt           time.Time
	TechnicianTimeOffID pgtype.UUID
}

func (q *Queries) DeleteTechnicianTimeOff(ctx context.Context, arg DeleteTechnicianTimeOffParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTechnicianTimeOff, arg.DeletedAt, arg.TechnicianTimeOffID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTechnicianTimeOff = `-- name: GetTechnicianTimeOff :one

SELECT technician_time_off_id, technician_id, starts_at, ends_at, reason, created_at, deleted_at
FROM appointment_scheduler.technician_time_off
WHERE technician_time_off_id = $1 AND deleted_at IS NULL
`

// technician time off CRUD queries.
func (q *Queries) GetTechnicianTimeOff(ctx context.Context, technicianTimeOffID pgtype.UUID) (AppointmentSchedulerTechnicianTimeOff, error) {
	row := q.db.QueryRow(ctx, getTechnicianTimeOff, technicianTimeOffID)
	var i AppointmentSchedulerTechnicianTimeOff
	err := row.Scan(
		&i.TechnicianTimeOffID,
		&i.TechnicianID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Reason,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTechnicianTimeOff = `-- name: UpdateTechnicianTimeOff :execrows
UPDATE appointment_scheduler.technician_time_off
SET technician_id = $1, starts_at = $2, ends_at = $3, reason = $4
WHERE technician_time_off_id = $5 AND deleted_at IS NULL
`

type UpdateTechnicianTimeOffParams struct {
	TechnicianID        pgtype.UUID
	StartsAt            time.Time
	EndsAt              time.Time
	Reason              *string
	TechnicianTimeOffID pgtype.UUID
}

func (q *Queries) UpdateTechnicianTimeOff(ctx context.Context, arg UpdateTechnicianTimeOffParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTechnicianTimeOff,
		arg.TechnicianID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Reason,
		arg.TechnicianTimeOffID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
