// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: technicians.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTechnicians = `-- name: CreateTechnicians :exec
INSERT INTO appointment_scheduler.technicians (technician_id, user_id, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateTechniciansParams struct {
	TechnicianID pgtype.UUID
	UserID       pgtype.UUID
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateTechnicians(ctx context.Context, arg CreateTechniciansParams) error {
	_, err := q.db.Exec(ctx, createTechnicians,
		arg.TechnicianID,
		arg.UserID,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTechnicians = `-- name: DeleteTechnicians :execrows
UPDATE appointment_scheduler.technicians
SET deleted_at = $1::timestamptz
WHERE technician_id = $2 AND deleted_at IS NULL
`

type DeleteTechniciansParams struct {
	DeletedAt    time.Time
	TechnicianID pgtype.UUID
}

func (q *Queries) DeleteTechnicians(ctx context.Context, arg DeleteTechniciansParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTechnicians, arg.DeletedAt, arg.TechnicianID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTechnicians = `-- name: GetTechnicians :one

SELECT technician_id, user_id, is_active, created_at, updated_at, deleted_at
FROM appointment_scheduler.technicians
WHERE technician_id = $1 AND deleted_at IS NULL
`

type GetTechniciansRow struct {
	TechnicianID pgtype.UUID
	UserID       pgtype.UUID
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    pgtype.Timestamptz
}

// technicians CRUD queries.
func (q *Queries) GetTechnicians(ctx context.Context, technicianID pgtype.UUID) (GetTechniciansRow, error) {
	row := q.db.QueryRow(ctx, getTechnicians, technicianID)
	var i GetTechniciansRow
	err := row.Scan(
		&i.TechnicianID,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTechnicians = `-- name: UpdateTechnicians :execrows
UPDATE appointment_scheduler.technicians
SET user_id = $1, is_active = $2, updated_at = $3
WHERE technician_id = $4 AND deleted_at IS NULL
`

type UpdateTechniciansParams struct {
	UserID       pgtype.UUID
	IsActive     bool
	UpdatedAt    time.Time
	TechnicianID pgtype.UUID
}

func (q *Queries) UpdateTechnicians(ctx context.Context, arg UpdateTechniciansParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTechnicians,
		arg.UserID,
		arg.IsActive,
		arg.UpdatedAt,
		arg.TechnicianID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
