// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: technicians.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTechnician = `-- name: CreateTechnician :one
WITH created_user AS (
  INSERT INTO appointment_scheduler.users (
    user_id, auth_user_id, name, phone, email, dealership_id, is_active, created_at, updated_at
  ) VALUES (
    $1, '00000000-0000-0000-0000-000000000000', $2,
    $3, $4, $5, $6,
    $7, $8
  ) RETURNING user_id, name, phone, email, is_active, created_at, updated_at
), created_technician AS (
  INSERT INTO appointment_scheduler.technicians (technician_id, user_id, is_active, created_at, updated_at)
  SELECT $9, user_id, is_active, created_at, updated_at FROM created_user
  RETURNING technician_id, user_id, is_active, created_at, updated_at
)
SELECT created_technician.technician_id, created_technician.user_id, created_user.name,
  created_user.phone, created_user.email, created_technician.is_active,
  created_technician.created_at, created_technician.updated_at
FROM created_technician JOIN created_user USING (user_id)
`

type CreateTechnicianParams struct {
	UserID       pgtype.UUID
	Name         string
	Phone        *string
	Email        *string
	DealershipID pgtype.UUID
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	TechnicianID pgtype.UUID
}

type CreateTechnicianRow struct {
	TechnicianID pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	Phone        *string
	Email        *string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateTechnician(ctx context.Context, arg CreateTechnicianParams) (CreateTechnicianRow, error) {
	row := q.db.QueryRow(ctx, createTechnician,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.DealershipID,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TechnicianID,
	)
	var i CreateTechnicianRow
	err := row.Scan(
		&i.TechnicianID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTechnicians = `-- name: CreateTechnicians :exec
INSERT INTO appointment_scheduler.technicians (technician_id, user_id, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateTechniciansParams struct {
	TechnicianID pgtype.UUID
	UserID       pgtype.UUID
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateTechnicians(ctx context.Context, arg CreateTechniciansParams) error {
	_, err := q.db.Exec(ctx, createTechnicians,
		arg.TechnicianID,
		arg.UserID,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deactivateTechnicianForDealership = `-- name: DeactivateTechnicianForDealership :execrows
UPDATE appointment_scheduler.technicians SET is_active = FALSE, updated_at = $1
WHERE technician_id = $2 AND deleted_at IS NULL
  AND user_id IN (
    SELECT user_id FROM appointment_scheduler.users
    WHERE dealership_id = $3 AND deleted_at IS NULL
  )
`

type DeactivateTechnicianForDealershipParams struct {
	UpdatedAt    time.Time
	TechnicianID pgtype.UUID
	DealershipID pgtype.UUID
}

func (q *Queries) DeactivateTechnicianForDealership(ctx context.Context, arg DeactivateTechnicianForDealershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateTechnicianForDealership, arg.UpdatedAt, arg.TechnicianID, arg.DealershipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTechnicians = `-- name: DeleteTechnicians :execrows
UPDATE appointment_scheduler.technicians
SET deleted_at = $1::timestamptz
WHERE technician_id = $2 AND deleted_at IS NULL
`

type DeleteTechniciansParams struct {
	DeletedAt    time.Time
	TechnicianID pgtype.UUID
}

func (q *Queries) DeleteTechnicians(ctx context.Context, arg DeleteTechniciansParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTechnicians, arg.DeletedAt, arg.TechnicianID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveSchedulerEmployeeDealership = `-- name: GetActiveSchedulerEmployeeDealership :one
SELECT users.dealership_id
FROM appointment_scheduler.users
WHERE users.auth_user_id = $1
  AND users.is_active AND users.deleted_at IS NULL
`

func (q *Queries) GetActiveSchedulerEmployeeDealership(ctx context.Context, authUserID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveSchedulerEmployeeDealership, authUserID)
	var dealership_id pgtype.UUID
	err := row.Scan(&dealership_id)
	return dealership_id, err
}

const getActiveSchedulerEmployeeID = `-- name: GetActiveSchedulerEmployeeID :one
SELECT users.user_id
FROM appointment_scheduler.users
WHERE users.auth_user_id = $1
  AND users.is_active AND users.deleted_at IS NULL
`

func (q *Queries) GetActiveSchedulerEmployeeID(ctx context.Context, authUserID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveSchedulerEmployeeID, authUserID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getGlobalAdminDealership = `-- name: GetGlobalAdminDealership :one
SELECT users.dealership_id
FROM appointment_scheduler.users
JOIN appointment_scheduler.user_roles ON user_roles.user_id = users.user_id
JOIN appointment_scheduler.roles ON roles.role_id = user_roles.role_id
WHERE users.auth_user_id = $1
  AND users.is_active AND users.deleted_at IS NULL
  AND user_roles.deleted_at IS NULL
  AND roles.code = 'admin' AND roles.deleted_at IS NULL
`

func (q *Queries) GetGlobalAdminDealership(ctx context.Context, authUserID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getGlobalAdminDealership, authUserID)
	var dealership_id pgtype.UUID
	err := row.Scan(&dealership_id)
	return dealership_id, err
}

const getTechnicianForDealership = `-- name: GetTechnicianForDealership :one
SELECT technicians.technician_id, technicians.user_id, users.name, users.phone, users.email,
  technicians.is_active, technicians.created_at, technicians.updated_at
FROM appointment_scheduler.technicians
JOIN appointment_scheduler.users ON users.user_id = technicians.user_id
WHERE technicians.technician_id = $1
  AND users.dealership_id = $2
  AND technicians.deleted_at IS NULL AND users.deleted_at IS NULL
`

type GetTechnicianForDealershipParams struct {
	TechnicianID pgtype.UUID
	DealershipID pgtype.UUID
}

type GetTechnicianForDealershipRow struct {
	TechnicianID pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	Phone        *string
	Email        *string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetTechnicianForDealership(ctx context.Context, arg GetTechnicianForDealershipParams) (GetTechnicianForDealershipRow, error) {
	row := q.db.QueryRow(ctx, getTechnicianForDealership, arg.TechnicianID, arg.DealershipID)
	var i GetTechnicianForDealershipRow
	err := row.Scan(
		&i.TechnicianID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTechnicians = `-- name: GetTechnicians :one
SELECT technician_id, user_id, is_active, created_at, updated_at, deleted_at
FROM appointment_scheduler.technicians
WHERE technician_id = $1 AND deleted_at IS NULL
`

type GetTechniciansRow struct {
	TechnicianID pgtype.UUID
	UserID       pgtype.UUID
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetTechnicians(ctx context.Context, technicianID pgtype.UUID) (GetTechniciansRow, error) {
	row := q.db.QueryRow(ctx, getTechnicians, technicianID)
	var i GetTechniciansRow
	err := row.Scan(
		&i.TechnicianID,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hasActiveAppointmentOverlap = `-- name: HasActiveAppointmentOverlap :one
SELECT EXISTS (
  SELECT 1
  FROM appointment_scheduler.appointments
  WHERE technician_id = $1
    AND deleted_at IS NULL
    AND status IN ('requested', 'checked_in', 'in_progress')
    AND starts_at < $2
    AND ends_at > $3
)
`

type HasActiveAppointmentOverlapParams struct {
	TechnicianID pgtype.UUID
	EndsAt       time.Time
	StartsAt     time.Time
}

func (q *Queries) HasActiveAppointmentOverlap(ctx context.Context, arg HasActiveAppointmentOverlapParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveAppointmentOverlap, arg.TechnicianID, arg.EndsAt, arg.StartsAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasFutureActiveTechnicianAppointments = `-- name: HasFutureActiveTechnicianAppointments :one
SELECT EXISTS (
  SELECT 1 FROM appointment_scheduler.appointments
  WHERE technician_id = $1 AND deleted_at IS NULL
    AND status IN ('requested', 'checked_in', 'in_progress') AND ends_at > $2
)
`

type HasFutureActiveTechnicianAppointmentsParams struct {
	TechnicianID pgtype.UUID
	Now          time.Time
}

func (q *Queries) HasFutureActiveTechnicianAppointments(ctx context.Context, arg HasFutureActiveTechnicianAppointmentsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasFutureActiveTechnicianAppointments, arg.TechnicianID, arg.Now)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listTechniciansForDealership = `-- name: ListTechniciansForDealership :many
SELECT technicians.technician_id, technicians.user_id, users.name, users.phone, users.email,
  technicians.is_active, technicians.created_at, technicians.updated_at
FROM appointment_scheduler.technicians
JOIN appointment_scheduler.users ON users.user_id = technicians.user_id
WHERE users.dealership_id = $1
  AND ($2::boolean IS NULL OR technicians.is_active = $2::boolean)
  AND technicians.deleted_at IS NULL AND users.deleted_at IS NULL
ORDER BY technicians.created_at, technicians.technician_id
LIMIT $4 OFFSET $3
`

type ListTechniciansForDealershipParams struct {
	DealershipID pgtype.UUID
	IsActive     *bool
	Offset       int32
	Limit        int32
}

type ListTechniciansForDealershipRow struct {
	TechnicianID pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	Phone        *string
	Email        *string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ListTechniciansForDealership(ctx context.Context, arg ListTechniciansForDealershipParams) ([]ListTechniciansForDealershipRow, error) {
	rows, err := q.db.Query(ctx, listTechniciansForDealership,
		arg.DealershipID,
		arg.IsActive,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTechniciansForDealershipRow{}
	for rows.Next() {
		var i ListTechniciansForDealershipRow
		if err := rows.Scan(
			&i.TechnicianID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTechnicianSchedule = `-- name: LockTechnicianSchedule :exec

SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// technicians CRUD queries.
func (q *Queries) LockTechnicianSchedule(ctx context.Context, technicianID string) error {
	_, err := q.db.Exec(ctx, lockTechnicianSchedule, technicianID)
	return err
}

const updateTechnicianForDealership = `-- name: UpdateTechnicianForDealership :one
WITH updated_user AS (
  UPDATE appointment_scheduler.users SET name = $1, phone = $2,
    email = $3, is_active = $4, updated_at = $5
  WHERE user_id = (
    SELECT user_id FROM appointment_scheduler.technicians
    WHERE appointment_scheduler.technicians.technician_id = $6
      AND appointment_scheduler.technicians.deleted_at IS NULL
  ) AND dealership_id = $7 AND deleted_at IS NULL
  RETURNING user_id, name, phone, email
), updated_technician AS (
  UPDATE appointment_scheduler.technicians SET is_active = $4, updated_at = $5
  WHERE technician_id = $6 AND user_id IN (SELECT user_id FROM updated_user)
  RETURNING technician_id, user_id, is_active, created_at, updated_at
)
SELECT updated_technician.technician_id, updated_technician.user_id, updated_user.name,
  updated_user.phone, updated_user.email, updated_technician.is_active,
  updated_technician.created_at, updated_technician.updated_at
FROM updated_technician JOIN updated_user USING (user_id)
`

type UpdateTechnicianForDealershipParams struct {
	Name         string
	Phone        *string
	Email        *string
	IsActive     bool
	UpdatedAt    time.Time
	TechnicianID pgtype.UUID
	DealershipID pgtype.UUID
}

type UpdateTechnicianForDealershipRow struct {
	TechnicianID pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	Phone        *string
	Email        *string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) UpdateTechnicianForDealership(ctx context.Context, arg UpdateTechnicianForDealershipParams) (UpdateTechnicianForDealershipRow, error) {
	row := q.db.QueryRow(ctx, updateTechnicianForDealership,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.IsActive,
		arg.UpdatedAt,
		arg.TechnicianID,
		arg.DealershipID,
	)
	var i UpdateTechnicianForDealershipRow
	err := row.Scan(
		&i.TechnicianID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTechnicians = `-- name: UpdateTechnicians :execrows
UPDATE appointment_scheduler.technicians
SET user_id = $1, is_active = $2, updated_at = $3
WHERE technician_id = $4 AND deleted_at IS NULL
`

type UpdateTechniciansParams struct {
	UserID       pgtype.UUID
	IsActive     bool
	UpdatedAt    time.Time
	TechnicianID pgtype.UUID
}

func (q *Queries) UpdateTechnicians(ctx context.Context, arg UpdateTechniciansParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTechnicians,
		arg.UserID,
		arg.IsActive,
		arg.UpdatedAt,
		arg.TechnicianID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
