// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: technician_shifts.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTechnicianShifts = `-- name: CreateTechnicianShifts :exec
INSERT INTO appointment_scheduler.technician_shifts (technician_shift_id, technician_id, day_of_week, starts_at, ends_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateTechnicianShiftsParams struct {
	TechnicianShiftID pgtype.UUID
	TechnicianID      pgtype.UUID
	DayOfWeek         int16
	StartsAt          pgtype.Time
	EndsAt            pgtype.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) CreateTechnicianShifts(ctx context.Context, arg CreateTechnicianShiftsParams) error {
	_, err := q.db.Exec(ctx, createTechnicianShifts,
		arg.TechnicianShiftID,
		arg.TechnicianID,
		arg.DayOfWeek,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTechnicianShifts = `-- name: DeleteTechnicianShifts :execrows
UPDATE appointment_scheduler.technician_shifts
SET deleted_at = $1::timestamptz
WHERE technician_shift_id = $2 AND deleted_at IS NULL
`

type DeleteTechnicianShiftsParams struct {
	DeletedAt         time.Time
	TechnicianShiftID pgtype.UUID
}

func (q *Queries) DeleteTechnicianShifts(ctx context.Context, arg DeleteTechnicianShiftsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTechnicianShifts, arg.DeletedAt, arg.TechnicianShiftID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTechnicianShifts = `-- name: GetTechnicianShifts :one

SELECT technician_shift_id, technician_id, day_of_week, starts_at, ends_at, created_at, updated_at, deleted_at
FROM appointment_scheduler.technician_shifts
WHERE technician_shift_id = $1 AND deleted_at IS NULL
`

type GetTechnicianShiftsRow struct {
	TechnicianShiftID pgtype.UUID
	TechnicianID      pgtype.UUID
	DayOfWeek         int16
	StartsAt          pgtype.Time
	EndsAt            pgtype.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         pgtype.Timestamptz
}

// technician shifts CRUD queries.
func (q *Queries) GetTechnicianShifts(ctx context.Context, technicianShiftID pgtype.UUID) (GetTechnicianShiftsRow, error) {
	row := q.db.QueryRow(ctx, getTechnicianShifts, technicianShiftID)
	var i GetTechnicianShiftsRow
	err := row.Scan(
		&i.TechnicianShiftID,
		&i.TechnicianID,
		&i.DayOfWeek,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTechnicianShifts = `-- name: UpdateTechnicianShifts :execrows
UPDATE appointment_scheduler.technician_shifts
SET technician_id = $1, day_of_week = $2, starts_at = $3, ends_at = $4, updated_at = $5
WHERE technician_shift_id = $6 AND deleted_at IS NULL
`

type UpdateTechnicianShiftsParams struct {
	TechnicianID      pgtype.UUID
	DayOfWeek         int16
	StartsAt          pgtype.Time
	EndsAt            pgtype.Time
	UpdatedAt         time.Time
	TechnicianShiftID pgtype.UUID
}

func (q *Queries) UpdateTechnicianShifts(ctx context.Context, arg UpdateTechnicianShiftsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTechnicianShifts,
		arg.TechnicianID,
		arg.DayOfWeek,
		arg.StartsAt,
		arg.EndsAt,
		arg.UpdatedAt,
		arg.TechnicianShiftID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
