// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_roles.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserRoles = `-- name: CreateUserRoles :exec
INSERT INTO appointment_scheduler.user_roles (user_role_id, user_id, role_id, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateUserRolesParams struct {
	UserRoleID pgtype.UUID
	UserID     pgtype.UUID
	RoleID     pgtype.UUID
	CreatedAt  time.Time
}

func (q *Queries) CreateUserRoles(ctx context.Context, arg CreateUserRolesParams) error {
	_, err := q.db.Exec(ctx, createUserRoles,
		arg.UserRoleID,
		arg.UserID,
		arg.RoleID,
		arg.CreatedAt,
	)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :execrows
UPDATE appointment_scheduler.user_roles
SET deleted_at = $1::timestamptz
WHERE user_role_id = $2 AND deleted_at IS NULL
`

type DeleteUserRolesParams struct {
	DeletedAt  time.Time
	UserRoleID pgtype.UUID
}

func (q *Queries) DeleteUserRoles(ctx context.Context, arg DeleteUserRolesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserRoles, arg.DeletedAt, arg.UserRoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserRoles = `-- name: GetUserRoles :one

SELECT user_role_id, user_id, role_id, created_at, deleted_at
FROM appointment_scheduler.user_roles
WHERE user_role_id = $1 AND deleted_at IS NULL
`

// user roles CRUD queries.
func (q *Queries) GetUserRoles(ctx context.Context, userRoleID pgtype.UUID) (AppointmentSchedulerUserRole, error) {
	row := q.db.QueryRow(ctx, getUserRoles, userRoleID)
	var i AppointmentSchedulerUserRole
	err := row.Scan(
		&i.UserRoleID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserRoles = `-- name: UpdateUserRoles :execrows
UPDATE appointment_scheduler.user_roles
SET user_id = $1, role_id = $2
WHERE user_role_id = $3 AND deleted_at IS NULL
`

type UpdateUserRolesParams struct {
	UserID     pgtype.UUID
	RoleID     pgtype.UUID
	UserRoleID pgtype.UUID
}

func (q *Queries) UpdateUserRoles(ctx context.Context, arg UpdateUserRolesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserRoles, arg.UserID, arg.RoleID, arg.UserRoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
