// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedulerAdmin = `-- name: CreateSchedulerAdmin :one
WITH created_user AS (
  INSERT INTO appointment_scheduler.users (
    user_id,
    auth_user_id,
    name,
    phone,
    email,
    dealership_id,
    is_active,
    created_at,
    updated_at
  )
  VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    TRUE,
    $7,
    $8
  )
  RETURNING user_id, auth_user_id, name, phone, email, dealership_id, is_active, created_at, updated_at
), created_role AS (
  INSERT INTO appointment_scheduler.user_roles (user_role_id, user_id, role_id, created_at)
  SELECT $9, created_user.user_id, $10, $7
  FROM created_user
)
SELECT user_id, auth_user_id, name, phone, email, dealership_id, is_active, created_at, updated_at
FROM created_user
`

type CreateSchedulerAdminParams struct {
	UserID       pgtype.UUID
	AuthUserID   pgtype.UUID
	Name         string
	Phone        *string
	Email        *string
	DealershipID pgtype.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserRoleID   pgtype.UUID
	RoleID       pgtype.UUID
}

type CreateSchedulerAdminRow struct {
	UserID       pgtype.UUID
	AuthUserID   pgtype.UUID
	Name         string
	Phone        *string
	Email        *string
	DealershipID pgtype.UUID
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateSchedulerAdmin(ctx context.Context, arg CreateSchedulerAdminParams) (CreateSchedulerAdminRow, error) {
	row := q.db.QueryRow(ctx, createSchedulerAdmin,
		arg.UserID,
		arg.AuthUserID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.DealershipID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserRoleID,
		arg.RoleID,
	)
	var i CreateSchedulerAdminRow
	err := row.Scan(
		&i.UserID,
		&i.AuthUserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.DealershipID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSchedulerUser = `-- name: CreateSchedulerUser :one
WITH created_user AS (
  INSERT INTO appointment_scheduler.users (
    user_id, auth_user_id, name, email, dealership_id, is_active, created_at, updated_at
  ) VALUES (
    $1, $2, $3, $4,
    $5, TRUE, $6, $7
  )
  RETURNING user_id, auth_user_id, name, email, dealership_id, is_active, created_at, updated_at
), created_role AS (
  INSERT INTO appointment_scheduler.user_roles (user_role_id, user_id, role_id, created_at)
  SELECT $8, user_id, $9, $6
  FROM created_user
)
SELECT user_id, auth_user_id, name, email, dealership_id, is_active, created_at, updated_at
FROM created_user
`

type CreateSchedulerUserParams struct {
	UserID       pgtype.UUID
	AuthUserID   pgtype.UUID
	Name         string
	Email        *string
	DealershipID pgtype.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserRoleID   pgtype.UUID
	RoleID       pgtype.UUID
}

type CreateSchedulerUserRow struct {
	UserID       pgtype.UUID
	AuthUserID   pgtype.UUID
	Name         string
	Email        *string
	DealershipID pgtype.UUID
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateSchedulerUser(ctx context.Context, arg CreateSchedulerUserParams) (CreateSchedulerUserRow, error) {
	row := q.db.QueryRow(ctx, createSchedulerUser,
		arg.UserID,
		arg.AuthUserID,
		arg.Name,
		arg.Email,
		arg.DealershipID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserRoleID,
		arg.RoleID,
	)
	var i CreateSchedulerUserRow
	err := row.Scan(
		&i.UserID,
		&i.AuthUserID,
		&i.Name,
		&i.Email,
		&i.DealershipID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUsers = `-- name: CreateUsers :exec
INSERT INTO appointment_scheduler.users (user_id, auth_user_id, name, phone, email, dealership_id, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUsersParams struct {
	UserID       pgtype.UUID
	AuthUserID   pgtype.UUID
	Name         string
	Phone        *string
	Email        *string
	DealershipID pgtype.UUID
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateUsers(ctx context.Context, arg CreateUsersParams) error {
	_, err := q.db.Exec(ctx, createUsers,
		arg.UserID,
		arg.AuthUserID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.DealershipID,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUsers = `-- name: DeleteUsers :execrows
UPDATE appointment_scheduler.users
SET deleted_at = $1::timestamptz
WHERE user_id = $2 AND deleted_at IS NULL
`

type DeleteUsersParams struct {
	DeletedAt time.Time
	UserID    pgtype.UUID
}

func (q *Queries) DeleteUsers(ctx context.Context, arg DeleteUsersParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUsers, arg.DeletedAt, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSchedulerUserByAuthUserID = `-- name: GetSchedulerUserByAuthUserID :one

SELECT user_id
FROM appointment_scheduler.users
WHERE auth_user_id = $1
  AND deleted_at IS NULL
`

// users CRUD queries.
func (q *Queries) GetSchedulerUserByAuthUserID(ctx context.Context, authUserID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSchedulerUserByAuthUserID, authUserID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUsers = `-- name: GetUsers :one
SELECT user_id, auth_user_id, name, phone, email, dealership_id, is_active, created_at, updated_at, deleted_at
FROM appointment_scheduler.users
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetUsersRow struct {
	UserID       pgtype.UUID
	AuthUserID   pgtype.UUID
	Name         string
	Phone        *string
	Email        *string
	DealershipID pgtype.UUID
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetUsers(ctx context.Context, userID pgtype.UUID) (GetUsersRow, error) {
	row := q.db.QueryRow(ctx, getUsers, userID)
	var i GetUsersRow
	err := row.Scan(
		&i.UserID,
		&i.AuthUserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.DealershipID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const isActiveCustomerEmployee = `-- name: IsActiveCustomerEmployee :one
SELECT EXISTS (
  SELECT 1
  FROM appointment_scheduler.users AS users
  JOIN appointment_scheduler.user_roles AS user_roles ON user_roles.user_id = users.user_id
  JOIN appointment_scheduler.roles AS roles ON roles.role_id = user_roles.role_id
  WHERE users.auth_user_id = $1
    AND users.auth_user_id IS NOT NULL
    AND users.is_active
    AND users.deleted_at IS NULL
    AND user_roles.deleted_at IS NULL
    AND roles.deleted_at IS NULL
    AND roles.code IN ('admin', 'dealer', 'staff')
)
`

func (q *Queries) IsActiveCustomerEmployee(ctx context.Context, authUserID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveCustomerEmployee, authUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isActiveSchedulerAdmin = `-- name: IsActiveSchedulerAdmin :one
SELECT EXISTS (
  SELECT 1
  FROM appointment_scheduler.users AS users
  JOIN appointment_scheduler.user_roles AS user_roles
    ON user_roles.user_id = users.user_id
  JOIN appointment_scheduler.roles AS roles
    ON roles.role_id = user_roles.role_id
  WHERE users.auth_user_id = $1
    AND users.is_active
    AND users.deleted_at IS NULL
    AND user_roles.deleted_at IS NULL
    AND roles.code = 'admin'
    AND roles.deleted_at IS NULL
)
`

func (q *Queries) IsActiveSchedulerAdmin(ctx context.Context, authUserID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveSchedulerAdmin, authUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isActiveSchedulerAdminForDealership = `-- name: IsActiveSchedulerAdminForDealership :one
SELECT EXISTS (
  SELECT 1
  FROM appointment_scheduler.users AS users
  JOIN appointment_scheduler.user_roles AS user_roles ON user_roles.user_id = users.user_id
  JOIN appointment_scheduler.roles AS roles ON roles.role_id = user_roles.role_id
  WHERE users.auth_user_id = $1
    AND users.dealership_id = $2
    AND users.is_active
    AND users.deleted_at IS NULL
    AND user_roles.deleted_at IS NULL
    AND roles.code = 'admin'
    AND roles.deleted_at IS NULL
)
`

type IsActiveSchedulerAdminForDealershipParams struct {
	AuthUserID   pgtype.UUID
	DealershipID pgtype.UUID
}

func (q *Queries) IsActiveSchedulerAdminForDealership(ctx context.Context, arg IsActiveSchedulerAdminForDealershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveSchedulerAdminForDealership, arg.AuthUserID, arg.DealershipID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateUsers = `-- name: UpdateUsers :execrows
UPDATE appointment_scheduler.users
SET auth_user_id = $1, name = $2, phone = $3, email = $4, dealership_id = $5, is_active = $6, updated_at = $7
WHERE user_id = $8 AND deleted_at IS NULL
`

type UpdateUsersParams struct {
	AuthUserID   pgtype.UUID
	Name         string
	Phone        *string
	Email        *string
	DealershipID pgtype.UUID
	IsActive     bool
	UpdatedAt    time.Time
	UserID       pgtype.UUID
}

func (q *Queries) UpdateUsers(ctx context.Context, arg UpdateUsersParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUsers,
		arg.AuthUserID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.DealershipID,
		arg.IsActive,
		arg.UpdatedAt,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
