// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicles.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicles = `-- name: CreateVehicles :exec
INSERT INTO appointment_scheduler.vehicles (vehicle_id, customer_id, vin, registration_plate, make, model, model_year, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateVehiclesParams struct {
	VehicleID         pgtype.UUID
	CustomerID        pgtype.UUID
	Vin               *string
	RegistrationPlate *string
	Make              string
	Model             string
	ModelYear         *int16
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) CreateVehicles(ctx context.Context, arg CreateVehiclesParams) error {
	_, err := q.db.Exec(ctx, createVehicles,
		arg.VehicleID,
		arg.CustomerID,
		arg.Vin,
		arg.RegistrationPlate,
		arg.Make,
		arg.Model,
		arg.ModelYear,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteVehicles = `-- name: DeleteVehicles :execrows
UPDATE appointment_scheduler.vehicles
SET deleted_at = $1::timestamptz
WHERE vehicle_id = $2 AND deleted_at IS NULL
`

type DeleteVehiclesParams struct {
	DeletedAt time.Time
	VehicleID pgtype.UUID
}

func (q *Queries) DeleteVehicles(ctx context.Context, arg DeleteVehiclesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVehicles, arg.DeletedAt, arg.VehicleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVehicles = `-- name: GetVehicles :one

SELECT vehicle_id, customer_id, vin, registration_plate, make, model, model_year, created_at, updated_at, deleted_at
FROM appointment_scheduler.vehicles
WHERE vehicle_id = $1 AND deleted_at IS NULL
`

type GetVehiclesRow struct {
	VehicleID         pgtype.UUID
	CustomerID        pgtype.UUID
	Vin               *string
	RegistrationPlate *string
	Make              string
	Model             string
	ModelYear         *int16
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         pgtype.Timestamptz
}

// vehicles CRUD queries.
func (q *Queries) GetVehicles(ctx context.Context, vehicleID pgtype.UUID) (GetVehiclesRow, error) {
	row := q.db.QueryRow(ctx, getVehicles, vehicleID)
	var i GetVehiclesRow
	err := row.Scan(
		&i.VehicleID,
		&i.CustomerID,
		&i.Vin,
		&i.RegistrationPlate,
		&i.Make,
		&i.Model,
		&i.ModelYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateVehicles = `-- name: UpdateVehicles :execrows
UPDATE appointment_scheduler.vehicles
SET customer_id = $1, vin = $2, registration_plate = $3, make = $4, model = $5, model_year = $6, updated_at = $7
WHERE vehicle_id = $8 AND deleted_at IS NULL
`

type UpdateVehiclesParams struct {
	CustomerID        pgtype.UUID
	Vin               *string
	RegistrationPlate *string
	Make              string
	Model             string
	ModelYear         *int16
	UpdatedAt         time.Time
	VehicleID         pgtype.UUID
}

func (q *Queries) UpdateVehicles(ctx context.Context, arg UpdateVehiclesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVehicles,
		arg.CustomerID,
		arg.Vin,
		arg.RegistrationPlate,
		arg.Make,
		arg.Model,
		arg.ModelYear,
		arg.UpdatedAt,
		arg.VehicleID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
