// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"time"
)

type AuthRole struct {
	RoleID string
	Name   string
}

type AuthUser struct {
	UserID          string
	FullName        string
	Email           *string
	EmailLookup     []byte
	HashedPassword  string
	HashedPassword1 string
	HashedPassword2 string
	TokenVer        int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Status          string
}

type AuthUserRole struct {
	UserID    string
	RoleID    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
