// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"time"
)

type AuthRole struct {
	RoleID string
	Name   string
}

type AuthUser struct {
	UserID            string
	FullName          string
	Email             []byte
	EmailLookup       []byte
	EmailTo           *string
	HashedPassword    string
	HashedPassword1   string
	HashedPassword2   string
	TokenVer          int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Status            string
	EmailPassword     []byte
	EmailPasswordSalt []byte
}

type AuthUserRole struct {
	UserID    string
	RoleID    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
