// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbmodels

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO auth.users (
  user_id, email, email_password, email_password_salt, email_lookup, full_name, hashed_password, hashed_password_1,
  hashed_password_2, token_ver, status, created_at, updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13
)
`

type CreateUserParams struct {
	UserID            string
	Email             []byte
	EmailPassword     []byte
	EmailPasswordSalt []byte
	EmailLookup       []byte
	FullName          string
	HashedPassword    string
	HashedPassword1   string
	HashedPassword2   string
	TokenVer          int32
	Status            string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.EmailPassword,
		arg.EmailPasswordSalt,
		arg.EmailLookup,
		arg.FullName,
		arg.HashedPassword,
		arg.HashedPassword1,
		arg.HashedPassword2,
		arg.TokenVer,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createUserRole = `-- name: CreateUserRole :exec
INSERT INTO auth.user_roles (
  user_id, role_id, created_at, updated_at
) SELECT
  $1,
  roles.role_id,
  $2,
  $3
FROM auth.roles
WHERE roles.name = $4
ON CONFLICT (user_id) DO UPDATE
SET role_id = EXCLUDED.role_id,
    updated_at = EXCLUDED.updated_at
`

type CreateUserRoleParams struct {
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
	RoleName  string
}

func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error {
	_, err := q.db.Exec(ctx, createUserRole,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.RoleName,
	)
	return err
}

const getPasswordEncryptedEmail = `-- name: GetPasswordEncryptedEmail :one
SELECT email_password, email_password_salt
FROM auth.users
WHERE user_id = $1
`

type GetPasswordEncryptedEmailRow struct {
	EmailPassword     []byte
	EmailPasswordSalt []byte
}

func (q *Queries) GetPasswordEncryptedEmail(ctx context.Context, userID string) (GetPasswordEncryptedEmailRow, error) {
	row := q.db.QueryRow(ctx, getPasswordEncryptedEmail, userID)
	var i GetPasswordEncryptedEmailRow
	err := row.Scan(&i.EmailPassword, &i.EmailPasswordSalt)
	return i, err
}

const getRefreshUserByID = `-- name: GetRefreshUserByID :one
SELECT users.user_id, users.email, users.full_name, users.hashed_password,
       users.hashed_password_1, users.hashed_password_2, users.token_ver,
       users.status, users.created_at, users.updated_at, roles.name AS role
FROM auth.users
JOIN auth.user_roles ON auth.user_roles.user_id = users.user_id
JOIN auth.roles ON roles.role_id = auth.user_roles.role_id
WHERE users.user_id = $1
`

type GetRefreshUserByIDRow struct {
	UserID          string
	Email           []byte
	FullName        string
	HashedPassword  string
	HashedPassword1 string
	HashedPassword2 string
	TokenVer        int32
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Role            string
}

func (q *Queries) GetRefreshUserByID(ctx context.Context, userID string) (GetRefreshUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getRefreshUserByID, userID)
	var i GetRefreshUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.FullName,
		&i.HashedPassword,
		&i.HashedPassword1,
		&i.HashedPassword2,
		&i.TokenVer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getSignInUserByEmail = `-- name: GetSignInUserByEmail :one
SELECT users.user_id, users.email, users.full_name, users.hashed_password,
       users.hashed_password_1, users.hashed_password_2, users.token_ver,
       users.status, users.created_at, users.updated_at, roles.name AS role
FROM auth.users
JOIN auth.user_roles ON auth.user_roles.user_id = users.user_id
JOIN auth.roles ON roles.role_id = auth.user_roles.role_id
WHERE users.email_lookup = $1
`

type GetSignInUserByEmailRow struct {
	UserID          string
	Email           []byte
	FullName        string
	HashedPassword  string
	HashedPassword1 string
	HashedPassword2 string
	TokenVer        int32
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Role            string
}

func (q *Queries) GetSignInUserByEmail(ctx context.Context, emailLookup []byte) (GetSignInUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getSignInUserByEmail, emailLookup)
	var i GetSignInUserByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.FullName,
		&i.HashedPassword,
		&i.HashedPassword1,
		&i.HashedPassword2,
		&i.TokenVer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, email, full_name, hashed_password, hashed_password_1,
       hashed_password_2, token_ver, status, created_at, updated_at
FROM auth.users
WHERE email_lookup = $1
`

type GetUserByEmailRow struct {
	UserID          string
	Email           []byte
	FullName        string
	HashedPassword  string
	HashedPassword1 string
	HashedPassword2 string
	TokenVer        int32
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, emailLookup []byte) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, emailLookup)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.FullName,
		&i.HashedPassword,
		&i.HashedPassword1,
		&i.HashedPassword2,
		&i.TokenVer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, email, full_name, hashed_password, hashed_password_1,
       hashed_password_2, token_ver, status, created_at, updated_at
FROM auth.users
WHERE user_id = $1
`

type GetUserByIDRow struct {
	UserID          string
	Email           []byte
	FullName        string
	HashedPassword  string
	HashedPassword1 string
	HashedPassword2 string
	TokenVer        int32
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, userID string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.FullName,
		&i.HashedPassword,
		&i.HashedPassword1,
		&i.HashedPassword2,
		&i.TokenVer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT roles.name
FROM auth.user_roles
JOIN auth.roles ON roles.role_id = auth.user_roles.role_id
WHERE auth.user_roles.user_id = $1
`

func (q *Queries) GetUserRole(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, userID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const hasAnyUser = `-- name: HasAnyUser :one
SELECT EXISTS (
  SELECT 1
  FROM auth.users
)
`

func (q *Queries) HasAnyUser(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasAnyUser)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockInitialAccountCreation = `-- name: LockInitialAccountCreation :exec
SELECT pg_advisory_xact_lock(48201945)
`

func (q *Queries) LockInitialAccountCreation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockInitialAccountCreation)
	return err
}

const storeDeliveryEmail = `-- name: StoreDeliveryEmail :execrows
UPDATE auth.users
SET email_to = $1
WHERE user_id = $2
`

type StoreDeliveryEmailParams struct {
	EmailTo *string
	UserID  string
}

func (q *Queries) StoreDeliveryEmail(ctx context.Context, arg StoreDeliveryEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, storeDeliveryEmail, arg.EmailTo, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE auth.users
SET full_name = $1,
    hashed_password = $2,
    hashed_password_1 = $3,
    hashed_password_2 = $4,
    token_ver = $5,
    status = $6,
    updated_at = $7
WHERE user_id = $8
`

type UpdateUserParams struct {
	FullName        string
	HashedPassword  string
	HashedPassword1 string
	HashedPassword2 string
	TokenVer        int32
	Status          string
	UpdatedAt       time.Time
	UserID          string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.FullName,
		arg.HashedPassword,
		arg.HashedPassword1,
		arg.HashedPassword2,
		arg.TokenVer,
		arg.Status,
		arg.UpdatedAt,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPasswordAndEmail = `-- name: UpdateUserPasswordAndEmail :execrows
UPDATE auth.users
SET email_password = $1,
    email_password_salt = $2,
    hashed_password = $3,
    hashed_password_1 = $4,
    hashed_password_2 = $5,
    token_ver = $6,
    updated_at = $7
WHERE user_id = $8
`

type UpdateUserPasswordAndEmailParams struct {
	EmailPassword     []byte
	EmailPasswordSalt []byte
	HashedPassword    string
	HashedPassword1   string
	HashedPassword2   string
	TokenVer          int32
	UpdatedAt         time.Time
	UserID            string
}

func (q *Queries) UpdateUserPasswordAndEmail(ctx context.Context, arg UpdateUserPasswordAndEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPasswordAndEmail,
		arg.EmailPassword,
		arg.EmailPasswordSalt,
		arg.HashedPassword,
		arg.HashedPassword1,
		arg.HashedPassword2,
		arg.TokenVer,
		arg.UpdatedAt,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
